### ISSUE TITLE
Modules to consider adding

### ISSUE THREAD

**Issue by vsoch** [singularityhub/singularity-hpc#22]
- [x] scientific packages from [autumus](https://github.com/orgs/autamus/packages) (which are spack)
 - subset of https://github.com/poldracklab/lmod_modules that map to https://bids-apps.neuroimaging.io/apps/
 - look on HPC clusters and do `module spider` and find matching containers for scientific apps

**Comment by marcodelapierre** [comment]
As many as possible of quay.io/biocontainers
(the official repository of bioinformatics containers from https://biocontainers.pro)

Together with some colleagues, we're going to work on a few recipes from this repo in the next few weeks

**Comment by vsoch** [comment]
I can also help a ton with this, but over the weekend! I wasn't aware that biocontainers moved over to quay (I added a bunch from Docker Hub!) In retrospect this makes sense - I moved most of my Docker Hub containers over to quay too!

**Comment by marcodelapierre** [comment]
Thanks, I will keep you posted!
