### ISSUE TITLE
Start releasing official tags/versions of shpc

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#370]
Self-explanatory ... this will facilitate broader adoption :-)

For what I am concerned, I would encourage one release after this round of small issues/PRs, and my review of the documentation/help (hopefully 1st week of June)

**Comment by vsoch** [comment]
@marcodelapierre do you mean here on GitHub releases? We do have regular releases on pypi. https://pypi.org/project/singularity-hpc/#history. I find it easier to maintain releases to just one place, but if you see a desire to do them here as well (is there an advantage?) we could discuss that.

**Comment by marcodelapierre** [comment]
Thanks Vanessa.

The main reason is that the recommended way to install on the docs, right now, is via `git clone` rather than pypi:

https://singularity-hpc.readthedocs.io/en/latest/getting_started/installation.html#getting-started-installation

Indeed, I did prefer the git way for the reasons you pointed out in the docs, and especially because in this way one also gets the registry, ready to be used as starting point for container deployment or for edits to recipes.

If git is still the preferred way, then it would be good to have git versioning, to enable an additional `git checkout $shpc_version` step in the installation process.
Or, if the pypi installation is now more viable, perhaps I'd suggest updating the docs accordingly.

If I think about another tool I am using for software deployment, Spack, it also has a similar installation process that is based on git rather than pypi.

**Comment by vsoch** [comment]
That's a good point! I'll make a release of the current main branch to GitHub and then update the docs to use it. I haven't figured out how to have pip splot out the same structure that we need.

**Comment by vsoch** [comment]
We now have two GitHub releases!

**Comment by marcodelapierre** [comment]
Yeyy!!
