### ISSUE TITLE
Suggested feature: direct editing option for the config file

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#375]
`shpc config` provides a scriptable way to edit key:value pairs.
In some situations, though, it can be handy to inspect/directly edit the `settings.yaml` file.

I am suggesting to add an option for this, i.e. `shpc config --edit` (no arguments).

**Comment by vsoch** [comment]
Added!

**Comment by marcodelapierre** [comment]
Tested the follwoing:

`shpc config --edit`: works!

`shpc config --edit set singularity_module:singularity`: opens the editor, silently ignores the following bit -- should it maybe fail, or print a warning?

`shpc config set singularity_module:singularity`: edits on the fly
However, I have also noticed there's an inconsistency with the help screen, which does not mention `set` at all:
```
$ shpc config -h
usage: shpc config [-h] [--edit] [params [params ...]]

positional arguments:
  params      one or more key value pairs, in format key:value to update.

optional arguments:
  -h, --help  show this help message and exit
  --edit      Edit a config directly.
```

Should then the syntax for `--edit` just become an `edit` sub-command, which is alternative to `add`?

**Comment by vsoch** [comment]
Hmm. I could see adding edit, but maybe if there are other things we'd want to quickly edit. I think for now let's keep it under config (and not allow extra arguments, your first example). I'll fix the help screen!

**Comment by marcodelapierre** [comment]
Oh, I agree that `shpc edit` might become useful later on. 

Let me clarify what I meant.
In the dev branch right now these are the possibilities:
```
shpc config set key:value

shpc config --edit
```
I suggest to switch to:
```
shpc config set key:value

shpc config edit
```
and I also suggest to fix the `-h` screen, which is not mentioning the `set` subcommand of `config` right now.

I did not suggest the 2nd syntax in the 1st place, because I had been fooled by the help screen :-)

**Comment by vsoch** [comment]
Ah gotcha, will update to `shpc config edit`. I'm not sure I have a good solution for adding more levels to the command (other than parsing the arguments myself) or updating the help. Right now it looks like:

```bash
usage: shpc config [-h] [params [params ...]]

positional arguments:
  params      shpc config get key:value, or shpc config get key, or shpc edit

optional arguments:
  -h, --help  show this help message and exit
```
If we could add another subparser easily to an already subparser it might work to add more detailed help, but for now this is what I could figure out!

**Comment by marcodelapierre** [comment]
oh I see, thanks  for the explanation :)

by any chance, could this be newlined for readability:
```
positional arguments:
  params      shpc config get key:value, or 
                     shpc config get key, or 
                     shpc edit

```

**Comment by vsoch** [comment]
Oh woot! I just figured out I can add the RawTextHelpFormatter to a subparser and it works akin to the main parser! Yes this is much better :)

```bash
usage: shpc config [-h] [params [params ...]]

positional arguments:
  params      Set or get a config value, or edit the config.
              shpc config get key:value
              shpc config get key
              shpc edit

optional arguments:
  -h, --help  show this help message and exit
```

**Comment by marcodelapierre** [comment]
Looks cool!
Just beware the typo above, line below `Set or get ..` should be `shpc config add key:value`

**Comment by vsoch** [comment]
Fixed.
