### ISSUE TITLE
Allow for script definition instead of alias

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#383]
**Describe the bug**

Attempting to use command aliases from SHPC modules in child shells (e.g. with Nextflow) causes an error, as they turn out to be undefined there.

First test: bash and LUA

**To Reproduce**

Setup and OK test:
```
shpc install biocontainers/samtools:v1.9-4-deb_cv1

module use <appropriate path>
module load 
biocontainers/samtools/v1.9-4-deb_cv1

type samtools
```

To get the ERROR: launch a new `bash` shell, and try `type samtools` again.

Fix as described here: https://github.com/CHPC-UofU/Lmod-setup/
For each shell function called <FUNCTION>, add:
```
if (myShellName() == "bash") then
 execute{cmd="export -f FUNCTION",modeA={"load"}}
end
```

Second test: bash and TCL

Now, with TCL it's tougher, because it's using `set-alias` ... aliases are worse to make work in child shells than shell functions. 
I tried a few tricks I knew (`bash -i`, `shopt -s expand_aliases`, ..), they did not work.

I see that Env Modules from version 4.2 supports a new feature, `set-function`: `https://modules.readthedocs.io/en/latest/modulefile.html`

However, my old Lmod 7.6.2 does not like it.
[update] : no Lmod version supports it so far: https://lmod.readthedocs.io/en/latest/051_tcl_modulefiles.html

Going ahead to have a look at csh.

**Comment by marcodelapierre** [comment]
Third test:  csh and LUA

seems like csh does not have proper shell functions, so lua falls back to creating aliases here.
Again, could not find a way to have them inherited in sub-processes so far.

**Comment by marcodelapierre** [comment]
It's good that there's a workaround for bash+lua anyway!

**Comment by marcodelapierre** [comment]
Going to document one more possible case, mentioned by the folks above, https://github.com/CHPC-UofU/Lmod-setup/    :  does `mpirun` like shell functions and aliases?

**Comment by marcodelapierre** [comment]
There might be another corner cases, i.e. when the application needs to be run with MPI, e.g. `mpirun` or Slurm `srun`, or whatsoever. 
Looks like these guys don't like shell functions neither (again pointed out first in the link above, https://github.com/CHPC-UofU/Lmod-setup/

Still think it's kind of a corner cases because, at least for what I've seen so far, MPI applications are not deployed in containers that often.

**Comment by marcodelapierre** [comment]
Last thing of this work week...

There might be a way to offer a workaround for the corner cases above (child processes with Tcl modules or Csh shells, MPI), that is enabling SHPC users to choose between two ways of making command aliases available:
- the current shell functions/aliases, or 
- standalone shell scripts wrappers

This could be a choice to be made  in the `settings.yaml`, e.g. `alias_deploy` `in_module` or `shell_scripts`, something like that.

**Comment by vsoch** [comment]
First for the bash /lua fix (which I think is reasonable to do!) I want to clarify that:

1. we are doing this for the alias names (e.g., samtools) only
2. we check for the shell to be just "bash" and not "/bin/bash"

In Jinja2 it would look like this:

```
{% if aliases %}
if (myShellName() == "bash") then
{% for alias in aliases %}execute{cmd="export -f {{ alias.entrypoint }}", modeA={"load"}}{% endfor %}
end{% endif %}
```
+1 to add scripts - but let's tackle that when we have a clear / definitive example - it will be hard to do without that.

**Comment by marcodelapierre** [comment]
> First for the bash /lua fix (which I think is reasonable to do!) I want to clarify that:
> 
> we are doing this for the alias names (e.g., samtools) only
> we check for the shell to be just "bash" and not "/bin/bash"

yep! :-)

**Comment by marcodelapierre** [comment]
> +1 to add scripts - but let's tackle that when we have a clear / definitive example - it will be hard to do without that.

sure, just shared the thought as it came up to me! also, one thing at a time will be more manageable :)
let me know what type of example you're after, I can detail that meanwhile

**Comment by vsoch** [comment]
Since nextflow inspired the need, we could start with that.

**Comment by marcodelapierre** [comment]
oh sure!

I expect that nextflow with lua modules will work already with the fix above plus the empty variable definitions from #382.
If modules are tcl though (e.g. a cluster with Env Modules) then another way is needed. 

Along the same lines, a second one can be an MPI application, with any module type.

I can work on some toy code samples!

**Comment by eburgueno** [comment]
Oh. I must be sleep-deprived. I should've read this issue before commenting on #404. Relevant to both anyway, but I'm glad that my idea of using scripts was not too radical.

**Comment by vsoch** [comment]
No worries @eburgueno I love that you've jumped in to share your experience and ideas!

**Comment by marcodelapierre** [comment]
Hi, I am back on this one, and I have actually done some work on this on the past few days.

Nextflow example: I have used a simple one for Singularity tutorials (link below), I think I can adapt it quickly for shpc modules. It needs 3 tools, fastqc, multiqc, salmon, for which I have already added SHPC yamls to this github a few months back.
Link: https://pawseysc.github.io/singularity-containers/41-workflow-engines/index.html

Now for the wrapper scripts..

**Comment by marcodelapierre** [comment]
> So first question - do we need "wrapper scripts" or could this be fully represented as just another alias - either explicitly asked for, or just generated by default? And second question - we probably would want to allow for variables like number of ranks, regardless of if it's a script or a prefix. Would that be an environment variable?

I think scripts would do better than aliases when needing to interact with mpirun/srun, mostly for a user experience/interface reason: if using wrapper scripts, the user experience is completely transparent to the usage of containers under the hood, there's not a single change to their workflow scripts/commands, eg
```
srun -N 2 -n 4 --other-options openfoam bla bla
```
remains the same.
On the other hand, if we go with aliases end users will be forced to change their scripts, ie the above might become:
```
SHPC_SRUN_VARIABLES="-N 2 -n 4 --other-options"
openfoam-srun bla bla
```
To me, this is not ideal.

The only price I can see having to be paid with scripts is generating a handful of extra files in the filesystem, for each containerised package. Overall though, the impact on the filesystem in terms of file count is still lower compared to a traditional installation.

Thoughts?


> Are these wrapper scripts general, or are they container specific? 

They are not specific, they can be written in a very general, templated way. 


> If they are container-specific, then I don't think it's weird to put alongside the module folder

You are right, the module directory is fine. I was worried that scripts might be confused for modulefiles, but from some tests I have done it does not seem to be the case.


Another extra comment I have is an extension to the context I provided in this issue at the start.
I said it's only for MPI, but I was imprecise, because when using the Slurm scheduler, end users should use srun also in other circumstances for appropriate HW resource allocation to the application, including multicore (multi-threaded) executions  and GPU accelerated ones.
Ultimately, some centres end up suggesting users to always srun for executing their applications.

Because MPI is not the unique scope for this, the proposed new option for wrapper scripts might just be an on/off one for all generated modules, in settings.yml. No need for a new "feature".
Eventually, and only eventually, we might add a third "mpi" case where only packages with "mpi" feature are impacted. This could be handy when running on system where there's no srun, and the scripts are really just needed for use with "mpirun" for MPI execution. 

I am going to open a PR shortly, with a first draft for this new wrapper scripts functionality :)

**Comment by vsoch** [comment]
@marcodelapierre amazing this is done! This was a huge effort and I want to thank you for your hard work and commitment!  Onward to fixing bugs and more cool things, haha.

**Comment by marcodelapierre** [comment]
Thank you @vsoch for your lead and contributions!
As in previous feature additions to this project, I have really enjoyed collaborating with you, and I have felt inspired by your constructive and enthusiastic attitude! ...and indeed, now ahead with bug fixing lol

**Comment by marcodelapierre** [comment]
This really made my day today! 
And now....I can't wait to see all of this deployed system-wide on Setonix, our upcoming Tier-1 Supercomputer here at Pawsey Centre!
