### ISSUE TITLE
Update "About" of this github repo

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#387]
Current:
```
Local filesystem registry for Singularity containers (intended for HPC) using LMOD. Works for users and admins.
```

would probably replace `LMOD` with `system modules`

**Comment by vsoch** [comment]
@marcodelapierre I just updated the add/docker branch to say:

```
DESCRIPTION = "Local registry intended for HPC using containers and system modules."
```
It originally was going to be a database, but when I added LMOD I realized I didn't need it :P
