### ISSUE TITLE
Export functions in Lua modules

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#390]
Just taking this one out of #383, 
as it can be addressed quickly.

This would allow SHPC Lua modules to work in Nextflow:

```
if (myShellName() == "bash") then
 execute{cmd="export -f FUNCTION",modeA={"load"}}
end
```

And this is the corresponding Jinja2 snippet you mentioned:
```
{% if aliases %}
if (myShellName() == "bash") then
{% for alias in aliases %}execute{cmd="export -f {{ alias.entrypoint }}", modeA={"load"}}{% endfor %}
end
{% endif %}
```

**Comment by vsoch** [comment]
Didn’t we add this? https://github.com/singularityhub/singularity-hpc/blob/8731bae44c8c69a49d618f9739cca142ce2535b4/shpc/main/modules/templates/singularity.lua#L68

Is something missing or not working? We can fix that up.

**Comment by marcodelapierre** [comment]
oh my bad!!

I was proof-reading a sample modulefile but missed it!!

Doing a Nextflow test right now! :-)

**Comment by marcodelapierre** [comment]
Yup, it works, amazing!
I tested both an interactive Nextflow execution, and a batched one with the cluster schedule (Slurm at Pawsey).
Both setups worked!
