### ISSUE TITLE
Question on conflict modules in generated modulefiles

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#395]
I was testing a modified `biocontainers/samtools:v1.9-4-deb_cv1` with a 2nd alias, just to check how aliases looked like (I added `bamtools: /usr/bin/bamtools`).

The aliases looked right both in Lua and Tcl, however I noticed that the conflict list grew with that additional alias, both for Lua and Tcl; for Lua:
```
conflict(myModuleName(),"samtools","bamtools")
```
for Tcl:
```
conflict biocontainers/samtools
conflict samtools
conflict bamtools
```

What is the rationale behind adding a conflict for each alias name? 
Also, why does the list look different for the two languages?

Thanks,

**Comment by vsoch** [comment]
I was thinking that there should always be a conflict if there is an equivalent alias. It's probably safe to remove the full name from tcl (e.g., biocontainers/samtools). Is this logical? What would happen if two loaded modules had the same alias but there was not a conflict defined?

**Comment by marcodelapierre** [comment]
I think it's probably one of those things where different people/groups will have a different take.
In the end, it's probably not a big deal, users would naturally adapt to whichever behaviour is required by the modules.

It's probably good to leave the full name though, it prevents from accidentally loading two versions of the same SHPC container module. So ... can it be added for Lua, too?
