### ISSUE TITLE
Notation for Lua/Tcl module languages

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#396]
These are just minor notation/documentation points:

1. in `settings.yaml`, there is the following:
```
# set a default module system
# Currently only lmod is supported. To request an additional system, 
# please open an issue https://github.com/singularityhub/singularity-hpc
module_sys: lmod
```
This should probably be updated to include tcl

2. I am wondering whether `lua` should be allowed as an equivalent option to `lmod`; the former could be more natural to use to some people, when having to pick which *language* they want SHPC to use for the modulefiles

**Comment by vsoch** [comment]
Will be updated soon! Currently, you can choose lmod, lua, or just None (and use the command line to specify). 
```
"module_sys": {"type": "string", "enum": ["lmod", "tcl", None]},`
```
It just doesn't say that in the settings file (the note there is old before I added it).
