### ISSUE TITLE
JOSS review

### ISSUE THREAD

**Issue by rcannood** [singularityhub/singularity-hpc#416]
Hi @vsoch !

Thanks for creating this. I think it will be of major use for many HPC admins. 

I was going through the functional claims of the manuscript. I noticed that, on a new instance, the `module load biocontainers/samtools` command ([paper.md#L54](https://github.com/singularityhub/singularity-hpc/blame/main/paper/paper.md#L54)) doesn't work because the command `module` isn't installed. This won't be an issue for HPC admins who want to start using `shpc` as they will probably have something in place already, but maybe it's not a bad idea to point to the install documentation of modules.

Kind regards,
Robrecht

**Comment by vsoch** [comment]
This is a good point! I realized that I had written a section that states this, but it drifted (and probably is hidden) in the development section here: https://singularity-hpc.readthedocs.io/en/latest/getting_started/developer-guide.html#development-or-testing. So to address, I've added a quick note to the README:

![image](https://user-images.githubusercontent.com/814322/123822184-4a2dd880-d8b9-11eb-83d5-645a4b23b833.png)

And more importantly, explicitly stated it in the install so the reader knows that the software is required, and the `module` command must be available:

https://singularity-hpc.readthedocs.io/en/latest/getting_started/installation.html

**Comment by rcannood** [comment]
Alright, thanks :+1:
