### ISSUE TITLE
trouble getting started (in particular modules)

### ISSUE THREAD

**Issue by zbeekman** [singularityhub/singularity-hpc#421]
**Describe the bug**

This might be a user error, but TLDR, I'm having trouble getting started--I'm not a modules/LMOD expert--and `module load biocontainers/samtools` isn't working. 

I installed shpc by cloning and `pip install -e .`.

```
$ shpc install biocontainers/samtools
$ module load biocontainers/samtools
ERROR: Unable to locate a modulefile for 'biocontainers/samtools'
```

I try

```
$ shpc config set lmod_base:/home/ibeekman/modules
lmod_base:/home/ibeekman/modules cannot be added to config: Additional properties are not allowed ('lmod_base' was unexpected)
```
 
I'm on Ubuntu 20.04 using `Modules Release 4.4.1`

**To Reproduce**
Steps to reproduce the behavior: See above

**Expected behavior**

**Version of Singularity and Singularity Registry HPC Client**

I followed the clone instructions from JOSS paper, so the default main or development branch

**Comment by vsoch** [comment]
You usually need to tell LMOD about the folder first with module use ./modules

**Comment by vsoch** [comment]
https://singularity-hpc.readthedocs.io/en/latest/getting_started/user-guide.html#quick-start

**Comment by vsoch** [comment]
And lmod_base is old! I see where it is in the docs and I’ll update it - should be just module_base

**Comment by zbeekman** [comment]
OK, so I think I also hadn't initialized environment modules in my dot files (maybe) but still no joy with `module use ...` I can see it adds that directory to the `$MODULEPATH` but `module avail` still shows nothing even though `shpc` created `biocontainers/samtools/v.....` but important question: I only see a `module.lua` file and I'm using TCL modules. Should it have given me a different/additional module file? Any ideas why it's still not showing up with `module avail`?

**Comment by vsoch** [comment]
Yeah! tcl is different module software, you need to tell shpc that. https://singularity-hpc.readthedocs.io/en/latest/getting_started/user-guide.html#module-software

**Comment by zbeekman** [comment]
And I guess some additional directions about initializing lmod or TCL modules and `module use` etc. would be helpful in the getting started documentation for those with less experience (on HPC systems either there are very specific directions, or you get a set of default dot files that take care of this). Oh, I'll read the link you just posted. Putting this somewhere early (or a pointer to it) in the installation or elsewhere in getting started might be helpful.

**Comment by vsoch** [comment]
I agree! I think it should be alongside installation and quick start.

**Comment by zbeekman** [comment]
Also, in the paper, on the bottom of the second page, there is an example command that I think is wrong:

`$ biocontainer-samtools-shell` ➡️ `$ samtools-shell`

I get command not found for the first command, but `samtools-shell` works.

**Comment by vsoch** [comment]
Ah thank you! Yes that was changed between when the paper was submit and now! Will fix that in the current PR.

**Comment by vsoch** [comment]
https://github.com/singularityhub/singularity-hpc/pull/422

**Comment by zbeekman** [comment]
I'm trying to test the `run-notebook` capability, it might be cool to add a line above the `$ run-notebook` line with the install & module activation commands, something like:

```
$ shpc install jupyter/minimal-notebook && module load jupyter/minimal-notebook
$ run-notebook
```

I tried this but it seems `module load jupyter/minimal-notebook` fails for me with a complaint about the HOME variable (which is set in my default Ubuntu 20.04 Bash shell). Maybe an issue with the module file definition and a syntax difference between TCL & LMOD?

**Comment by alecbcs** [comment]
Interesting! Can you copy the complaint message about the HOME variable into here?

**Comment by zbeekman** [comment]
yeah, alacritty in my VM won't put it in the right clip board to get over to macOS, one second, let me log in to GH on the VM

**Comment by zbeekman** [comment]
@alecbcs here is the error message I get:

```
module show jupyter
  -------------------------------------------------------------------
  /mnt/hgfs/Sandbox/singularity-hpc/modules/jupyter/minimal-notebook/4.0/module.tcl:

  setenv          SINGULARITY_OPTS {}
  setenv          SINGULARITY_COMMAND_OPTS {}
  conflict        jupyter/minimal-notebook
  conflict        run-notebook
  setenv          SINGULARITY_SHELL /bin/sh
  set-alias       minimal-notebook-shell {singularity ${SINGULARITY_OPTS} shell ${SINGULARITY_COMMAND_OPTS} -s /bin/sh -B /mnt/hgfs/Sandbox/singularity-hpc/m  odules/jupyter/minimal-notebook/4.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh  /mnt/hgfs/Sandbox/singularity-hpc/modules/jupyter/minimal-notebook/4.0/jupyt  er-minimal-notebook-4.0-sha256:6f9d189494fe091700681eb39b429dfe1420ad0717697c2e2293779fcb80cd1e.sif}
  Module ERROR: can't read "HOME": no such variable
    In '/mnt/hgfs/Sandbox/singularity-hpc/modules/jupyter/minimal-notebook/4.0/module.tcl'
    Please contact <root@localhost>
```

**Comment by zbeekman** [comment]
or when I try to load it:

```
module load jupyter/minimal-notebook
  Loading jupyter/minimal-notebook/4.0/module.tcl
    Module ERROR: can't read "HOME": no such variable
      In '/mnt/hgfs/Sandbox/singularity-hpc/modules/jupyter/minimal-notebook/4.0/module.tcl'
      Please contact <root@localhost>
```

**Comment by vsoch** [comment]
Just curious, do you not have $HOME set?

**Comment by vsoch** [comment]
It's definitely in the command for jupyter, and not the module template:

```
options: --home ${HOME} --bind ${HOME}/.local:/home/joyvan/.local
```

**Comment by vsoch** [comment]
First try setting home if it's not set. Then try deleting that line in registry/jupyter/minimal-notebook and then installing and using and loading again:

```bash
$ shpc install jupyter/minimal-notebook
$ module use ./modules
$ module load jupyter/minimal-notebook
```
That's an interesting error - I've never seen a system without $HOME !

**Comment by zbeekman** [comment]
nope, $HOME is definitely set!

```
$ echo $HOME
/home/ibeekman
```

And I need to `$ shpc install --module-sys tcl jupyter/minimal-notebook` becuase I have TCL modules.

**Comment by zbeekman** [comment]
maybe its an issue b/c I'm crossing file systems? My default git sandbox/project directory is mounted in VMWare Fusion as a shared drive from macOS. Which is where I installed shpc and put the modules.

**Comment by vsoch** [comment]
oh that might be it. Maybe try a shell and then echo $HOME and see if it's there? And also try deleting the options line and just running as is. We definitely didn't develop shpc accounting for edge cases like different filesystems!

**Comment by vsoch** [comment]
> $ shpc install --module-sys tcl jupyter/minimal-notebook

If you set this in your config you shouldn't need to one-off it for each command:

```bash
$ shpc config set module_sys:tcl
```

**Comment by zbeekman** [comment]
> Maybe try a shell and then echo $HOME and see if it's there?

I'm not quite sure what you mean by "try a shell", isn't bash a shell? Do you mean a shell inside a container?

**Comment by vsoch** [comment]
yes, sorry! So the container should be in the modules folder alongside the .tcl or .lua file. You can just shell inside manually (with singularity) and look at the environment. If there is a $HOME there likely it's some issue with the filesystem. In that case, try removing the options and re-installing and reloading again.

**Comment by zbeekman** [comment]
If I get a shell in the jupyter/minimal-notebook singularity image I still have a home directory. The error message is definitely from the TCL modules. I suspect TCL is trying to dereference home, rather than pass it to the shell?

```
$ shpc shell jupyter/minimal-notebook
Singularity> echo $HOME
/home/ibeekman
Singularity> exit
```

To me, the error message sounds like it's expecting HOME to be set by my TCL modules initialization or somewhere else in the module file.

**Comment by vsoch** [comment]
For the minimal notebook could you try escaping:

```bash
  options: --home \${HOME} --bind \${HOME}/.local:/home/joyvan/.local
```

**Comment by vsoch** [comment]
You'll need to update the container.yaml and then install again

**Comment by vsoch** [comment]
oops should not close here until we figure out the jupyter issue! I think it's just an issue of needing to comment the envars. We would want to verify that, add the comment (backslashes) and then make sure it works still for lmod and tcl. I'm happy to update all the recipes with envars when we are sure!

**Comment by zbeekman** [comment]
I manually edited the installed `module.tcl` file. Multiple `$`s needed escaping and TCL modules was indeed trying to deference things that aren't variables.

I think you mean "escape" not "comment" but I can confirm that doing this in the `module.tcl` fixes the issue. Instances of `HOME` and `$(shuf ...)` and maybe one or two other places.

Where is `container.yml` defined/located?

**Comment by zbeekman** [comment]
(And I have no idea if escaping the $s that are supposed to dereference shell variables will break the LMOD implementation)

**Comment by vsoch** [comment]
It should be in `registry/jupyter/minimal-notebook/container.yaml` - the $HOME variables that are not properly escaped (commented, just kidding) are rendered from there. So if you update there, and re-install, there shouldn't be any erroneous ones.

**Comment by vsoch** [comment]
> (And I have no idea if escaping the $s that are supposed to dereference shell variables will break the LMOD implementation)

Don't worry I can test that!

**Comment by zbeekman** [comment]
Example PR with fix https://github.com/singularityhub/singularity-hpc/pull/424. I can confirm this resolves the issue. However a new issue has arisen when trying to run the command:

```
$ run-notebook
Traceback (most recent call last):
  File "/opt/conda/lib/python3.4/site-packages/traitlets/traitlets.py", line 432, in __get__
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/jupyter-notebook", line 6, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.4/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/traitlets/config/application.py", line 591, in launch_instance
    app.initialize(argv)
  File "<string>", line 2, in initialize
  File "/opt/conda/lib/python3.4/site-packages/traitlets/config/application.py", line 75, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/conda/lib/python3.4/site-packages/notebook/notebookapp.py", line 1005, in initialize
    self.init_configurables()
  File "/opt/conda/lib/python3.4/site-packages/notebook/notebookapp.py", line 804, in init_configurables
    connection_dir=self.runtime_dir,
  File "/opt/conda/lib/python3.4/site-packages/traitlets/traitlets.py", line 439, in __get__
    value = self._validate(obj, dynamic_default())
  File "/opt/conda/lib/python3.4/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/opt/conda/lib/python3.4/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/opt/conda/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.4/os.py", line 227, in makedirs
    makedirs(head, mode, exist_ok)
  File "/opt/conda/lib/python3.4/os.py", line 237, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/run/user'
```

Is this a permission error from within the container? I don't have an `/opt/conda` on my Ubuntu VM.

**Comment by vsoch** [comment]
Yes this looks like it wants write at /run/user, but can't get it. I think this might be a new error in addition to the one you showed! How is Singularity installed on your system? And then I would try:

```yaml
  options: --home \${HOME} --bind \${HOME}/.local:/home/joyvan/.local --bind /tmp/run:/run/user
```

**Comment by vsoch** [comment]
okay a quick update! The escaped vars don't work for me for LMOD, so we are going to need to add the escaping in the logic that generates the lmod file (just for tcl). And I reproduced the issue with run user, adding the bind seems to work:

```bash
$ mkdir -p /tmp/run
(env) (base) vanessa@vanessa-ThinkPad-T490s:~/Desktop/Code/singularity-hpc$ singularity exec -B /home/vanessa/Desktop/Code/singularity-hpc/modules/jupyter/minimal-notebook/4.0/99-shpc.sh:/.singularity.d/env/99-shpc.sh --home ${HOME} --bind ${HOME}/.local:/home/joyvan/.local --bind /tmp/run:/run/user /tmp/containers/jupyter/minimal-notebook/4.0/jupyter-minimal-notebook-4.0-sha256\:6f9d189494fe091700681eb39b429dfe1420ad0717697c2e2293779fcb80cd1e.sif jupyter notebook --no-browser --port=$(shuf -i 2000-65000 -n 1) --ip 0.0.0.0
[I 20:51:23.367 NotebookApp] Writing notebook server cookie secret to /run/user/1000/jupyter/notebook_cookie_secret
[W 20:51:23.408 NotebookApp] ipywidgets package not installed.  Widgets are unavailable.
[I 20:51:23.421 NotebookApp] Serving notebooks from local directory: /home/vanessa/Desktop/Code/singularity-hpc
[I 20:51:23.422 NotebookApp] 0 active kernels 
[I 20:51:23.422 NotebookApp] The IPython Notebook is running at: http://0.0.0.0:42896/
[I 20:51:23.422 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
```
But if we want shpc to be able to handle that cleanly, we likely need to say something like "bind /run/user to some random tmp directory made at runtime" which is a new feature / functionality - I'll work on this soon!

**Comment by zbeekman** [comment]
Need anything else from me?

**Comment by vsoch** [comment]
@zbeekman I opened a PR with a fix if you would be able to test! #425

**Comment by zbeekman** [comment]
Sure, on vacation through the end of the week, if I find a spare moment I’ll test but it may have to wait until the weekend.

**Comment by zbeekman** [comment]
@vsoch I think we can close this issue now, no? PR #425 fixed the TCL modules issue for jupyter/minimal-notebook. I upgraded to the `HEAD` of `main`, purged my modules, uninstalled `jupyter/minimal-notebook`, reinstalled it, did a `module load jupyter/minimal-notebook` and successfully ran the alias command from the JOSS paper: `run-notebook`.

I guess you may need to fix the escaping of `$` issue for TCL modules in other yaml recipes?

**Comment by vsoch** [comment]
@zbeekman the escaping happens in the template (which renders from the yaml) so if there are others that had the issue, another install should re-generate the updated recipe. This issue was general for getting started so I didn't want to close it until you were content with that.

**Comment by zbeekman** [comment]
Sorry, I didn't look at the code changes in the PR, but it looks like you probably fixed everything! It looks like you're using jinja for templating, awesome!!! My (limited) testing of the jupyter/minimal-notebook installation, TCL module, alias command, and running the actual notebook all passed with flying colors. So I think this/these issues are all resolved now unless I'm forgetting something? Any other testing you'd like me to do?

**Comment by vsoch** [comment]
Nope that was it! Thanks for checking back in! Are we all set to close this issue then?

**Comment by zbeekman** [comment]
Yes 😎
