### ISSUE TITLE
Angry Emacs user 🤣 

### ISSUE THREAD

**Issue by zbeekman** [singularityhub/singularity-hpc#423]
**Describe the bug**

`shpc config edit` should respect the `$EDITOR` environment variable.

**To Reproduce**
Steps to reproduce the behavior: Don't have `vim` installed on your system and run `shpc config edit`.

**Expected behavior**
Pick an editor based on `$EDITOR` or `$VISUAL` if set.

**Version of Singularity and Singularity Registry HPC Client**

Anything else?

This is not related to the JOSS paper review (it's not in scope) and I'm not actually angry at all, just trying to add a little humor to the issue title.

**Comment by vsoch** [comment]
You can do:

```bash
shpc config set config_editor:emacs
```
Does that not work?

**Comment by alecbcs** [comment]
Hahaha this is a fair point! Is `$EDITOR` standardized in Linux? It doesn't seem to be defined on my system.

@vsoch maybe we could set the editor initially based on the presence of binaries? Or set to `vi` to support the highest number of legacy systems that have `vi` but not `vim`? 

(And you answered @zbeekman look for `shpc config` before I could finish typing lol....may the typing speed wars continue....I think you're up by at least 2 or 3 on me at this point!)

**Comment by vsoch** [comment]
I'm not sure if it's standard, I don't have it on my Ubuntu:

```bash
$ echo $EDITOR
```
I figure it's safer to just have it be part of the shpc config. And unfortunately I'm an angry vim user so that's why I made it the default. It's a slightly passive aggressive push of my own editor preferences through my software. :laughing:

**Comment by vsoch** [comment]
If it's better, I could add a check for the editor existing first?

**Comment by zbeekman** [comment]
> Does that not work?

yes, that works.

**Comment by alecbcs** [comment]
What about a function in the setup script that checks for each of these? If one isn't found continue on to the next until you find one present, then set that as the default in the config?
1. vim
2. emacs
3. nano
4. vi

**Comment by zbeekman** [comment]
It's up to you, but I always thought `$VISUAL` and `$EDITOR` were standard conventions; they're mentioned in the bash manpages and a lot of software (like git) respects it.

**Comment by vsoch** [comment]
Okay, updated so there is at least a nice error message and command to run if an editor is missing.

**Comment by zbeekman** [comment]
(Just to reiterate, this is beyond scope of JOSS review, so I'm just a humble user with a bug report/feature request--the former if you're an Emacs user, the later if you're a vi user :smile: )

**Comment by alecbcs** [comment]
> It's up to you, but I always thought `$VISUAL` and `$EDITOR` were standard conventions; they're mentioned in the bash manpages and a lot of software (like git) respects it.

Sooo this is how I prevent myself from having to type `git config --global core.editor emacs` every time I setup a new system!

**Comment by zbeekman** [comment]
I think a pretty error message should be more than sufficient. I personally if you want to spiff up the logic, I would check for EDITOR and VISUAL then fallback to vim and an error message if everything is missing, but this probably adds unneeded complexity. `¯\_(ツ)_/¯` I'm happy to call the issue closed with a clear error message.

**Comment by vsoch** [comment]
Let's leave it open for visibility to see what others' think - if we do honor an EDITOR envar, then we would probably need to eliminate the config setting (or have it set to null) and then first check the environment, then look for a set of expected editors as @alecbcs suggested. But it is much less complex to just have one config setting that is updated once and then forgotten about.

**Comment by eburgueno** [comment]
I think you'd be safe by just honoring `$EDITOR`, user config, system config, or fallback to `[vi|vim]` if none are set; in that order. I've had a hard time trying to pinpoint its origins, but `EDITOR` is [mentioned](https://pubs.opengroup.org/onlinepubs/9699919799/) in POSIX as a variable
> frequently exported by widely used command interpreters and applications

so it might even predate POSIX itself.

**Comment by vsoch** [comment]
Yeah, I'm thinking people might like that in favor of the current setup. I'll definitely keep this in mind and probably update the functionality the next time I'm working on the library!

**Comment by vsoch** [comment]
hey angry Emacs user! I'll have this change in the next PR to shpc, sorry for the long wait!

**Comment by vsoch** [comment]
Please see https://github.com/singularityhub/singularity-hpc/pull/591 for added support for the EDITOR and VISUAL envars!

**Comment by vsoch** [comment]
Added with https://github.com/singularityhub/singularity-hpc/pull/591.
