### ISSUE TITLE
Documentation suggestion about config settings 

### ISSUE THREAD

**Issue by zbeekman** [singularityhub/singularity-hpc#426]
While reading the docs I didn’t see a table with a concise collection of supported options in the config file. A table of these options for quick reference, and the expected location of the config file (or how to query shpc for this info) would be valuable additions to the documentation. (And if I overlooked them a more prominent pointer to them in the getting started section might be helpful.) if such a table could automatically be generated from the source that would save you having to keep the documentation up to date in a separate location.

**Comment by vsoch** [comment]
This table is under setup https://singularity-hpc.readthedocs.io/en/latest/getting_started/user-guide.html#setup

**Comment by zbeekman** [comment]
Thanks for pointing me in the right direction. I may have some thoughts about making this more prominent sooner, but if I come up with anything useful I’ll propose the change in a PR. Thanks for getting back to me!

**Comment by vsoch** [comment]
That sounds great @zbeekman, thank you!
