### ISSUE TITLE
New "Feature": X11 applications

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#433]
As I was developing some registries recently, I brushed up on some old user cases I had encountered.

One of them is graphical applications making use of X11.
Context: if an X11 application is able to run on a system (either locally or remotely), what does it take to have it working from inside a container?

In my experience, the setup for a Singularity container is quite straightforward: all is needed is to bind mount the Xauthority file, eg: `-B ~/.Xauthority`

Proposed feature:
- config file: `x11: <path of Xauthority file>` (the above could be suggested in a comment as generally good value)
- container registry: `x11: true` (defaults to false)

I also had experience with deploying X11 applications with Docker, however there it was a bit trickier, with also requirements in the Dockerfile (xauth package) and a more articulated setup in the host. I can eventually retrieve some examples from my Github.

Possible user cases I have met: general purpose data analysis & vis (Octave, Gnuplot), domain specific visualisation (eg IGV in bioinformatics)

**Comment by vsoch** [comment]
Couldn't this also be supported just with a bind?

**Comment by marcodelapierre** [comment]
Yes, it can :)
Currently, in SHPC this can be done in 2 ways:
- bindpath in the config, which acts on all containers
- SINGULARITY_COMMAND_OPTS, which needs to be manually actioned by the user at each runtime

My thinking on a *feature* for this is along some of the principles around the gpu one, ie provide a higher level abstraction that can be applied on selected containers.
The feature can be managed by who admins the SHPC installation, and applied only to those containers that need it; it's entirely transparent to users.

That's why I see a benefit, for both x11 and the fake home (see issue #434)

**Comment by vsoch** [comment]
This could also be done on the level of individual container recipes, e.g., with options as seen here: https://github.com/singularityhub/singularity-hpc/blob/898bd1cc9f3ef7be083a136854194da11837a22a/registry/jupyter/pyspark-notebook/container.yaml#L13.

**Comment by vsoch** [comment]
If it comes down to an individual bind, and if it's relevant for specific containers, I'm inclined to want to put it there instead of adding a new feature (which is more complex).

**Comment by marcodelapierre** [comment]
Sure, that would do, I only have one observation. 
If all aliases for that container need it, it means a lot of repetition (3 lines per alias),  whereas the feature would be one for the entire container...what do you think?

**Comment by marcodelapierre** [comment]
Actually, second observation, which only holds for the fake home feature (#434).
That one would benefit from the possibility of customising the location of the fake home on a per site basis, which is something the administrator may want to take care of. In this context, it is probably handier if such setting can be set once in the config for all containers, rather than having to be browsed across all used recipes. Sure this view is biased by some implied practices we adopt here at Pawsey :)

**Comment by vsoch** [comment]
That's a good point! If you want to make a proposal for how to implement, I can definitely consider and work on it this weekend.

**Comment by marcodelapierre** [comment]
Idea for an X11 feature:

SHPC  settings:
```
container_features:
  x11: "<path-to-Xauthority>" # normally null, could be eg "~/.Xauthority"
```

Package recipe:
```
features:
  x11: true  # or false (default)
```

Implementation: when feature is "true" in the package recipe, and container_feature is different from null, for Singularity add the exec/run/shell flag `-B <value of x11 in settings>`.

For Docker/Podman, in my experience this bind mount is not enough to have the X11 GUI working, it requires setup in the host, and the xauth package in the container, so I would not implement for now (similar to how we did not implement the gpu feature)
