### ISSUE TITLE
Thoughts on the extended syntax for aliases

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#439]
I have realised one thing by looking at the alias here:

https://github.com/singularityhub/singularity-hpc/blob/898bd1cc9f3ef7be083a136854194da11837a22a/registry/jupyter/pyspark-notebook/container.yaml#L13

These options  will work with Singularity, but break with Podman/Docker.

Perhaps there should be also a key like `options_docker` ?

**Comment by vsoch** [comment]
oh that's a very good point! I think the fix will have to be to separate them out. I'll make some time this weekend!

**Comment by vsoch** [comment]
@marcodelapierre see https://github.com/singularityhub/singularity-hpc/pull/440!

**Comment by vsoch** [comment]
This was closed with #440
