### ISSUE TITLE
[Docs] minor update to install instructions needed

### ISSUE THREAD

**Issue by eburgueno** [singularityhub/singularity-hpc#445]
[Docs](https://singularity-hpc.readthedocs.io/en/latest/getting_started/installation.html#virtual-environment) need updating after #403:
```
$ shpc config set registry:~/shpc/registry
You cannot use 'set' for a list. Use add/remove instead.

$ shpc config add registry:~/shpc/registry
Warning: Check with shpc config edit - ordering of list can change.
Added registry to ~/shpc/registry
```

**Comment by vsoch** [comment]
Yes indeed! Would you care to contribute a PR at your convenience?

**Comment by eburgueno** [comment]
Can do, thought it seems wasteful to create a commit (and PR) to replace three characters. I'll try looking at the docs a little bit more for other enhancements.

**Comment by vsoch** [comment]
Haha ok (but I don’t think it’s that wasteful!) every little improvement is a step in the right direction, whether addition or subtraction.

**Comment by vsoch** [comment]
@eburgueno just checking in - are you still interested to contribute here?

**Comment by eburgueno** [comment]
@vsoch yes, sorry, it's been a busy time. I'll send something shortly.

**Comment by vsoch** [comment]
No worries! See the linked PR for my tiny update to address what you found - if there is more please open a PR, if not apologies for taking me so long to fix that.

**Comment by eburgueno** [comment]
That looks just like what I was about to suggest. Thank you for beating me to it!
