### ISSUE TITLE
Naming of the module.tcl files?

### ISSUE THREAD

**Issue by jacquikeane** [singularityhub/singularity-hpc#453]
Is there a reason why the module files are all named module.tcl in the software/version directory (first screenshot) instead of named as the version in the software directory (second screenshot)? The latter is the naming convention on all the HPC environments I have used to date.

![Screenshot from 2021-11-18 16-17-30](https://user-images.githubusercontent.com/872885/142454999-0b786ad3-fbf7-4756-a200-3fbfd77eb5e7.png)
![Screenshot from 2021-11-18 16-20-46](https://user-images.githubusercontent.com/872885/142455041-caeb8590-2873-425f-acc3-9b114fa5f647.png)

Also, is there anyway to configure the directory structure for organising the module files on disk? For example, remove the name of the registry?

**Comment by vsoch** [comment]
It was mostly a choice based on my inexperience with managing modules, and also so that they were programmatically discoverable! I would definitely be open to discussion and then work to refactoring this to 1. make the naming more akin to conventions, and 2. still maintain discoverability and organization. cc @marcodelapierre

**Comment by jacquikeane** [comment]
Yes I though that was the reason! (I see a default script for defining environment variables included with each application). Perhaps having all the files that are currently generated stored somewhere outside of the modules base directory and then under the modules base directory creating the hierarchy as it is now but symlinking to the module.tcl as the version would be an option? (this is a random suggestion, I have not looked the code or know enough about modules to know if symlinked files are an option)

With regard my other question on the organisational hierarchy/directory structure under the modules base directory, it would be really great to be able to configure this. I will open another issue to explain the use case.

**Comment by vsoch** [comment]
I think we can figure out something to try! I'll bring @marcodelapierre into the conversation - note he's in Australia so I normally chat with him later in the evening. We will work on this soon!

**Comment by marcodelapierre** [comment]
I get Jacqui point on conventions, let me start from a couple of aspects:
1. ability to request a default version (ideally, this would be a switch that can be turned on and off)
2. readability of the module list by users (the extra "module" bit reduces readability -- however note this seems the only way to disable default versions)

On the 1st one above, the recent change in #451 (no SHPC release yet) tackles it, through the setting "default_version" true/false, by adding that .version file as described in the PR (or related issue).

However, I get point 2. may be of interest, too.
One way to tackle both at once would be to maintain that new setting "default_version" above, but change the implementation.
In particular:
- case "false": the original shpc module tree: `/......./<tool>/<version>/module.{tcl,lua}`
- case "true": the module tree proposed by Jacqui: `/......./<tool>/<version>.{tcl,lua}` ; It is to be checked whether the .version file would still be needed or not.

Hope this can help :) 
Happy to chat further, these days I am just flattened by work...!!

I have another reflection to share , in a following comment below

**Comment by muffato** [comment]
This has been addressed by the views.

**Comment by vsoch** [comment]
I also tested not using the name, and it seemed to break things so I'm afraid I don't have a suggested fix for this (beyond views). Does anyone else have thoughts or should we close?

**Comment by vsoch** [comment]
oops did not mean to close :laughing:

**Comment by marcodelapierre** [comment]
As @muffato mentioned, I think we've addressed this one with the views feature, isn't it?
