### ISSUE TITLE
Passing commandline arguments to singularity containers?

### ISSUE THREAD

**Issue by jacquikeane** [singularityhub/singularity-hpc#454]
Not sure if this is a bug or something I am doing incorrectly. After using shpc to install bwa and running bwa index it returns me the output as if I had just run bwa.

![Screenshot from 2021-11-18 16-49-10](https://user-images.githubusercontent.com/872885/142459665-14964739-1221-40bd-9b6f-de6fa7f20797.png)

Below is a snippet from the module.tcl generated by shpc for the bioinformatics software bwa but this will apply to all software applications. How are the commandline arguments passed to the singularity container? Should the function and alias commands include ''"$@""? Or is this handled somewhere else? 

![Screenshot from 2021-11-18 16-44-19](https://user-images.githubusercontent.com/872885/142458890-c6974ba9-1e47-4b59-bf93-6e313ad96dec.png)

**Comment by vsoch** [comment]
This looks like a bug - @marcodelapierre added these new functions rather recently, and indeed we are missing the argument parsing at the end! https://github.com/singularityhub/singularity-hpc/blob/1b800836e8bd53150eba9da0474e0506b8b3318f/shpc/main/modules/templates/singularity.tcl#L81. We can definitely fix this up asap.

**Comment by vsoch** [comment]
@jacquikeane do you have the same issue for any of the other interactions (e.g., the -exec functionality) or is it just the aliases?

**Comment by jacquikeane** [comment]
Ah excellent thanks!

**Comment by jacquikeane** [comment]
> @jacquikeane do you have the same issue for any of the other interactions (e.g., the -exec functionality) or is it just the aliases?

I have only tested this with bash. And yes I am seeing the issue with all the other interactions.

**Comment by marcodelapierre** [comment]
@vsoch indeed seems just like the wildcard missing from the aliases/functions - I have tested lmod extensively, but clearly tcl not us much 

going to test your PR asap

**Comment by vsoch** [comment]
Thank you! I added `$*` where I thought it would be appropriate, and my questions are:

- did I miss any commands?
- do we need to account for the shell? E.g., in previous versions we had one version for csh and bash.

**Comment by marcodelapierre** [comment]
Will have a look as soon as I can.

Why didn't `$@` work? I am surprised!

**Comment by vsoch** [comment]
If I remember correctly, we had to use $* for csh and $@ for bash. I tried the latter first, but it errored and the first seems to work! But this might depend on the user shell? Anyoo let me know what you learn! And thank you again @jacquikeane for finding this bug - we can hopefully get it fixed up soon.

**Comment by marcodelapierre** [comment]
but here it's strange, because the lua templates have `$@` for all cases and it works,
whereas in the tcl template you had to put `$*` for all .. might disappear for quite a bit today, but will be back on this asap

**Comment by vsoch** [comment]
This should be fixed! Closing issue, please re-open and yell in my direction if there is an issue. Happy turkey day!
