### ISSUE TITLE
shpc is on conda-forge now

### ISSUE THREAD

**Issue by ngam** [singularityhub/singularity-hpc#464]
https://anaconda.org/conda-forge/singularity-hpc
https://github.com/conda-forge/singularity-hpc-feedstock

Like your work here, thanks a lot of a great piece of ware! Just fyi, singularity-hpc is now on conda-forge. You're more than welcome to join me in maintaining it --- just a pr away. And feel free to let me know if you have any issues you'd like me to address, etc. 

Peace

**Comment by vsoch** [comment]
Would love to! Could you please add me to the maintainers list on conda forge?

**Comment by vsoch** [comment]
And ping me on the PR I can take a look at the recipe and give feedback, etc.

**Comment by ngam** [comment]
Yep, will do now.

**Comment by vsoch** [comment]
Thank you @ngam this is so great! I'm happy to help approve and review updated versions as they come in.
