### ISSUE TITLE
Access to private Docker container registry

### ISSUE THREAD

**Issue by gq1** [singularityhub/singularity-hpc#465]
Is there a way I can pass the gitlab access token to `shpc install` command to access our private docker container registry?

I could `docker login` beforehand but the docker is not allowed on our farm.

Thanks.

**Comment by vsoch** [comment]
Ah I do think we could support this! The first thing I would try is to login to the Docker registry with singularity first, see: https://github.com/sylabs/singularity-userdocs/blob/master/singularity_and_docker.rst#singularity-cli-remote-command. And then create a container.yaml registry entry to install as is. If that doesn't work, try providing `--docker-login` to Singularity pull, which you can do by again tweaking the container.yaml to add `singularity_options` (see example highlighted here https://singularity-hpc.readthedocs.io/en/latest/getting_started/developer-guide.html?highlight=singularity_options#aliases). As a third alternative you could export them to the environment and also do the shpc install: https://github.com/sylabs/singularity-userdocs/blob/master/singularity_and_docker.rst#environment-variables.

Do you want to give those a try and report back? If we need for shpc to do an extra step to look (and add) the variables we can do that too. Either way we can write up some quick docs so the next person knows how to do it!

**Comment by gq1** [comment]
Thanks again for a quick response.

Method 1 or 2:
After I singularity login in, I can pull the image successfully.

But shpc install gives an error, it seems pull the image from docker.io, not from our private registry:

_FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://sanger/pathogens/fasta@sha256:06f56170a812cefe7bc50b2600128e97646a3a69d03a717316f907d2b6cb2d29: reading manifest sha256:06f56170a812cefe7bc50b2600128e97646a3a69d03a717316f907d2b6cb2d29 in docker.io/sanger/pathogens/fasta: errors:
denied: requested access to the resource is denied
unauthorized: authentication required_

`
docker: sanger/pathogens/fasta
url: https://gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/docker-images/fasta
maintainer: '@gq2'
description: fasta in sanger
latest:
  36.3.8h: sha256:06f56170a812cefe7bc50b2600128e97646a3a69d03a717316f907d2b6cb2d29
tags:
  36.3.8h: sha256:06f56170a812cefe7bc50b2600128e97646a3a69d03a717316f907d2b6cb2d29
aliases:
- name: fasta36
  command: /usr/local/bin/fasta36
  singularity_options: --docker-login
`

**Comment by gq1** [comment]
Method 3, I also can use singularity to pull the image but different error now:

FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://sanger/pathogens/fasta@sha256:06f56170a812cefe7bc50b2600128e97646a3a69d03a717316f907d2b6cb2d29: unable to retrieve auth token: invalid username/password: unauthorized: incorrect username or password

**Comment by gq1** [comment]
Sorry about the above.

I changed the module name and then everything works.

docker: gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/docker-images/fasta
url: https://gitlab-registry.internal.sanger.ac.uk/sanger-pathogens/docker-images/fasta

**Comment by gq1** [comment]
By the way, ask another problem about the module load.

We use environment module, and shpc module loading time around 8s per module, far more than other modules we defined.

Do you know any any particular reason? the alias defined as a bash function?

**Comment by vsoch** [comment]
Glad you figured it out! Is this worth writing up some docs for?

Hmm he slowness is concerning - any ideas @marcodelapierre ?

**Comment by gq1** [comment]
Probably this is a general practice for singularity but shpc not using the command line tool, that is why I am not sure. 

If you can mention in the doc any private docker image also works but needs singularity login not docker login, that will be good.

singularity_options --docker-login in the yaml file seems not needed.

the module name needs to follow the docker image url, I probably need to read more your documents.

Thank you very much and great tools to use. I have setup everything on our farm and will try to add more software.

**Comment by vsoch** [comment]
Yes! So the module name (under registry) is typically organized by the container URI. E.g.,: `quay.io/org/container` would follow that same folder structure (registry/quay.io/org/container/container.yaml). Something on Docker Hub would not need the registry name (registry/vanessa/salad).

Let me know if you have any requests for software, and we can definitely add a note to the docs about private registry containers.

**Comment by marcodelapierre** [comment]
On the module load slowness I don't know, I haven't experienced that.
Is it reproducible? If so, do you have a large directory tree inside the module root directory for shpc?
Also, maybe worth checking with the sys admins, for any system specific configuration that might explain that.

**Comment by vsoch** [comment]
My guess would be:

1. something with the module cache https://sourceforge.net/p/lmod/mailman/message/31045582/
2. something with the filesystem being stressed - at one of our clusters at Stanford we would have days when things would just lag badly, and ultimately it was something about filesystem metadata
3. A lot of entries in modulepath or missing directories, e.g., see https://github.com/easybuilders/easybuild-framework/issues/2226

Could you debug a little bit @gq1 and let us know what you find?

**Comment by gq1** [comment]
Thanks both.

I have two main module paths, one with 400 modules installed and shpc with about 10 installed.

Loading the modules from the large path with no time, and all the modules from shpc needs minimum 8s.

The large module location actually has longer path than shpc's module locaiton.

If I reset the modulepath only to shpc's modules, the performance is the same.

We don't use lmod, does TCL modules make any difference?

Here I attach some examples for samtools, you can see we have different versions of samtools installed in 3 locations:

```
$ module avail --contains samtools
-------------------------------------------------------- /software/modules ---------------------------------------------------------
common-apps/samtools/1.9-114  ISG/sanger-samtools-refpath

------------------------------------------ /software/treeoflife/pshpc/etc/modules/current ------------------------------------------
samtools/0.1.19--h94a8ba4_6  samtools/1.6--h244ad75_4  samtools/1.9--h91753b0_8
samtools/1.2                 samtools/1.9              samtools/1.14--hb421002_0

------------------------------------------------ /software/treeoflife/shpc/modules -------------------------------------------------
biocontainers/samtools/v1.9-4-deb_cv1/module.tcl  quay.io/biocontainers/samtools/1.14--hb421002_0/module.tcl
ghcr.io/autamus/samtools/1.14/module.tcl

$ time module load biocontainers/samtools/v1.9-4-deb_cv1/module.tcl
real	0m9.281s
user	0m7.530s
sys	0m1.666s
$ module unload biocontainers/samtools/v1.9-4-deb_cv1/module.tcl

$ time module load common-apps/samtools/1.9-114
real	0m0.029s
user	0m0.020s
sys	0m0.005s
$ module unload common-apps/samtools/1.9-114

$ time module load samtools/0.1.19--h94a8ba4_6
Module loaded. For more information run 'module help samtools/0.1.19--h94a8ba4_6'.
real	0m0.031s
user	0m0.021s
sys	0m0.007s
```

**Comment by vsoch** [comment]
hey @gq1 would you mind opening an issue on https://github.com/cea-hpc/modules with this last comming? And cc me and @marcodelapierre so we can follow along?

**Comment by gq1** [comment]
I have talked to our Sys Admin to see any problem from our side. Once we are clear the issue, I will raise a ticket for Modules.

But the module file from shpc with lots of contents, probably that is the reason as well?
