### ISSUE TITLE
Shebang long path issue when using Python installed by Spack

### ISSUE THREAD

**Issue by marcodelapierre** [singularityhub/singularity-hpc#470]
Installing SHPC by means of a Python deployment installed via Spack results in too long (>128 chars) shebangs in the `shpc` and `spython` executables, which in turn cause their execution to fail.

For example, with shpc:
```
$ shpc
-bash: /home/mdelapierre/.local/bin/shpc: /lus/joey/home/mdelapierre/Spack-sprints/v0.17.0_new/spack/opt/spack/cray-sles15-zen2/gcc-10.3.0/python-3.9.7-2nk3ozgzzug2mig: bad interpreter: No such file or directory
```
```
$ head -1 $(which shpc)
#!/lus/joey/home/mdelapierre/Spack-sprints/v0.17.0_new/spack/opt/spack/cray-sles15-zen2/gcc-10.3.0/python-3.9.7-2nk3ozgzzug2migecarn5ez4ppjov2oe/bin/python3.9
```

I can work around this by replacing the long shebang with `#!/usr/bin/env3 python3.9`. This requires that python to be in the PATH, of course.

Interestingly, I noticed that the python package `semver`, an shpc dependency, is able to work around this. So maybe the solution can be borrowed from them...?
1. Semver scenario 1: short python binary path:
    ```
    $ head -1 $(which pysemver)
    #!/pawsey/sles12sp3/apps/gcc/4.8.5/python/3.6.3/bin/python3.6
    ```
2. Semver scenario 2: long python binary path:
    ```
    head -2 $(which pysemver)
    #!/bin/sh
    '''exec' /lus/joey/home/mdelapierre/Spack-sprints/v0.17.0_new/spack/opt/spack/cray-sles15-zen2/gcc-10.3.0/python-3.9.7-2nk3ozgzzug2migecarn5ez4ppjov2oe/bin/python3.9 "$0" "$@"
    ' '''
    ```

**Comment by vsoch** [comment]
If you can figure out a solution we can document or support it here - I'm not a huge spack fan for Python so I don't have any insight I'm afraid.

**Comment by marcodelapierre** [comment]
Sure, I will see what I can find!

**Comment by marcodelapierre** [comment]
Could not find a simple solution to this.
Because I am using Python installed via Spack, I am ending up editing the shpc/spython shebangs using the `sbang` utility by the Spack team, designed to handle long shebangs.
For reference, see project here with its readme: https://github.com/spack/sbang

**Comment by vsoch** [comment]
oh neat! Yes I'm definitely familiar with sbang.
