### ISSUE TITLE
Logo color scheme?

### ISSUE THREAD

**Issue by surak** [singularityhub/singularity-hpc#492]
As I am in Germany, the color selection of the logo and of the documentation strikes me as something here is kind of a taboo. 

Do you know what I'm talking about?

**Comment by vsoch** [comment]
Singularity Hub (and associated tools) tend to be red and white https://singularityhub.github.io/, I'm not sure what you are talking about.

**Comment by surak** [comment]
You can delete this if you want, but the logo on the documentation does remind me of this

![image](https://user-images.githubusercontent.com/878399/152660394-4824a83d-0d94-4ff2-90f6-dacc8e3480b5.png)

**Comment by surak** [comment]
<img width="299" alt="Screen Shot 2022-02-05 at 23 04 01" src="https://user-images.githubusercontent.com/878399/152660472-83152ee2-9e5b-4d51-9a99-c8c42fdfcaff.png">

**Comment by vsoch** [comment]
I'm sorry that is what it reminds you of - I am Ashkenazi myself so I assure you that was not intended, and it's never crossed my mine nor has anyone else ever suggested that in the 5+ years these projects have been around. Red is one of my favorite colors, and white/black made sense for text. I'm honestly not sure how to respond to this.

**Comment by vsoch** [comment]
The only thing I can suggest is to tone down the red a little, so it's more like a burnt red of the background at https://singularityhub.github.io/. if you'd like to PR to make this change I would be happy to review it.

**Comment by vsoch** [comment]
Does this resolve the issue? 
![image](https://user-images.githubusercontent.com/814322/152664997-31da30ea-6538-4a5b-ab1c-760f3b5c8458.png)

**Comment by surak** [comment]
I’m fine with whatever you suggest - and to be honest, those colors do go well together. Too bad they were used in that way. It ruined the fun for everyone else. 

It was more of a “seriously nobody has noticed that yet?” 

This issue can be closed.
