### ISSUE TITLE
The latest version is not the latest in the registry yaml file

### ISSUE THREAD

**Issue by gq1** [singularityhub/singularity-hpc#493]
I just installed bwa-mem2 default version from the official registry, there is some warning message to use this version.

Then I found out the default version is not the latest version actually.
https://github.com/singularityhub/singularity-hpc/blob/main/registry/quay.io/biocontainers/bwa-mem2/container.yaml
https://quay.io/repository/biocontainers/bwa-mem2?tab=tags

I think more confusing with bwa:
https://github.com/singularityhub/singularity-hpc/blob/main/registry/quay.io/biocontainers/bwa/container.yaml
https://quay.io/repository/biocontainers/bwa?tab=tags

Could you have a look as well?

Thanks.

**Comment by vsoch** [comment]
@gq1 the updater runs once a month. It would be untenable to run every day or even week because some containers update nightly.

**Comment by vsoch** [comment]
@gq1 I see what you mean - their versioning is weird (3 comes before 17) but somehow it's the latest. I think we probably need to consider the date of the updated version - cc @alecbcs this looks like a bug with binoc - how do we fix it?

**Comment by gq1** [comment]
Less number of versions for bwa-mem2, maybe easier to fix first.

**Comment by vsoch** [comment]
It's not a manual set of work, it's an automated bot that does the updates, so we will need to fix him. See the shpc parser here https://github.com/autamus/binoc. @alecbcs will be able to help / advise!

**Comment by vsoch** [comment]
This looks to be fixed - thanks @gq1 ! We are testing a new updater so if you see any further issues please let us know!
