### ISSUE TITLE
Unwanted changes for setting.yml  when using shpc config command

### ISSUE THREAD

**Issue by gq1** [singularityhub/singularity-hpc#507]
Thank you very much for all the fixes and new features.

Today I did a full test from you latest branch pull-bug-fix.

Two small problems for setting.yml file when I run shpc config command:

A white space in the end of line in the original file:
```
# use for singularity aliases (set to null to disable)
-  singularity: singularity.sh
+  singularity: singularity.sh
```

This being changed automatically
```
# Add an extra custom template directory (searched first)
-  templates: null
+  templates:
```

**Comment by vsoch** [comment]
These were fixed last night if you want to test. https://github.com/singularityhub/singularity-hpc/pull/506

**Comment by vsoch** [comment]
@gq1 I added an extra strip to handle extra white space for config - but I'm having trouble understanding what the other issue is. And just to clarify, these are for #506. Could you be more specific about the issue you are seeing (e.g, show me?)

**Comment by gq1** [comment]
Thanks.

there are two `null` values for `wrapper_scripts:templates ` and `namespace`

When you run any `shpc config` command to change other values, the above two variables will be changed to empty from `null`

Here is the `git diff` after  `shpc config` 

```
   # Add an extra custom template directory (searched first)
-  templates: null
+  templates:

 # the module namespace you want to install from. E.g., if you have ghcr.io/autamus/clingo
 # and you set the namespace to ghcr.io/autamus, you can just do: shpc install clingo.
-namespace: null
+namespace:
```

**Comment by vsoch** [comment]
I think that’s fine. Does it cause an issue for you?

**Comment by gq1** [comment]
no, just want to check what changes I put into setting.yml

**Comment by vsoch** [comment]
Gotcha! So those two things are treated the same - as None when loaded into Python.

**Comment by muffato** [comment]
Thanks @vsoch : we were essentially surprised that `shpc config` is not idempotent, and slightly worried that they would be treated differently.
👍🏼
