### ISSUE TITLE
Option to make wrapper script executable for others

### ISSUE THREAD

**Issue by gq1** [singularityhub/singularity-hpc#512]
Currently the wrapper script is only executable for the owner. 
`-rwxr--r-- 1 tolsoft toladmin 478 Mar 14 19:57 samtools`

Can we have an option to make them executable for others?
I made the following changes:

```
diff --git a/shpc/utils/fileio.py b/shpc/utils/fileio.py
index b8c5bb30f..061e3f424 100644
--- a/shpc/utils/fileio.py
+++ b/shpc/utils/fileio.py
@@ -123,7 +123,7 @@ def write_file(filename, content, mode="w", exec=False):
         filey.writelines(content)
     if exec:
         st = os.stat(filename)
-        os.chmod(filename, st.st_mode | stat.S_IEXEC)
+        os.chmod(filename, st.st_mode | stat.S_IXOTH)
     return filename
```

**Comment by muffato** [comment]
I understand the issue with `S_IEXEC`, which is a synonym of `S_IXUSR` according to https://docs.python.org/3/library/stat.html , but `S_IXOTH` in theory only sets the bits for the _others_. What about using `S_IXUSR | S_IXGRP | S_IXOTH` to guarantee that everyone can execute it ?

**Comment by gq1** [comment]
@muffato Yes, that is right. 

Because I just updated the installation, the scripts already there, each time it just added the bit.

```
-        os.chmod(filename, st.st_mode | stat.S_IEXEC)
+        os.chmod(filename, st.st_mode | stat.S_IEXEC | stat.S_IXGRP | stat.S_IXOTH)
```

**Comment by vsoch** [comment]
Actually it's before the work day, I can throw in a quick PR if you can review. Thanks!

**Comment by vsoch** [comment]
@gq1 and @muffato please check out https://github.com/singularityhub/singularity-hpc/pull/513 it should have your fixes!

**Comment by gq1** [comment]
Thanks @vsoch

**Comment by muffato** [comment]
Thank you @vsoch !
