### ISSUE TITLE
questions: module load and container interaction

### ISSUE THREAD

**Issue by radiantone** [singularityhub/singularity-hpc#526]
Trying to install redis container from here https://singularityhub.github.io/singularity-hpc/r/redis/
But doesn't work.

(venv) (base) [dgovoni@cooleylogin1 singularity-hpc]$ ls -l modules/
total 1
drwxr-xr-x 3 dgovoni users 512 Mar 25 12:00 redis
(venv) (base) [dgovoni@cooleylogin1 singularity-hpc]$ ls -l modules/redis/
total 1
drwxr-xr-x 2 dgovoni users 512 Mar 25 12:01 6.2.3-alpine
(venv) (base) [dgovoni@cooleylogin1 singularity-hpc]$ module use ./modules
(venv) (base) [dgovoni@cooleylogin1 singularity-hpc]$ module load redis/6.2.3-alpine
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'redis/6.2.3-alpine'
(venv) (base) [dgovoni@cooleylogin1 singularity-hpc]$ 

(venv) (base) [dgovoni@cooleylogin1 singularity-hpc]$ module avail
locate_module.c(1229):ERROR:106: Magic cookie '#%Module' missing in './modules/redis/.version'
locate_module.c(1229):ERROR:106: Magic cookie '#%Module' missing in './modules/redis/.version'

--------------------------------------------------------------------- /usr/share/Modules/modulefiles ----------------------------------------------------------------------
dot         module-git  module-info modules     null        use.own

**Comment by vsoch** [comment]
That looks like a bug that it doesn't like the .version file - what version are you using? We are doing extensive work on this in #517 but it's not ready yet! My suggestion for now is to delete the file. @marcodelapierre what say you?

**Comment by vsoch** [comment]
Also did you make sure to change the config to specify the correct module software?

**Comment by radiantone** [comment]
I just followed the instructions on the web page. Beyond that I'm not sure what other steps to do.

**Comment by vsoch** [comment]
Okay so:

What is your module software? LMOD or TCL (traditional "modules")

The default is lmod. So if you use TCL you need to do:

```bash
shpc config set module_sys:tcl
```
per instruction here in [install](https://singularity-hpc.readthedocs.io/en/latest/getting_started/installation.html). But if you already did that and this returns tcl:

```bash
$ shpc config get module_sys
```
Then your module software is good to go! In which case please just delete the .version file for now, there must be a version discrepancy that your version of TCL doesn't like the empty .version. Let me know the result of that! And in the future, the PR I referenced should handle this.

**Comment by radiantone** [comment]
```
$ shpc config get module_sys
module_sys                     lmod
```
I deleted the .version file and tried again.
```
$ module load redis/6.2.3-alpine
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'redis/6.2.3-alpine'
```

**Comment by vsoch** [comment]
Right, so I think if I'm reading your output correctly, you are using TCL but your shpc thinks it's lmod. So you need to do:

```
shpc config set module_sys:tcl
shpc config get module_sys
# verify you see "tcl" and not "lmod"
```
and then reinstall the module. What you did is install an lmod recipe for tcl so it's not going to work.

**Comment by vsoch** [comment]
Let me know if this solves your issue! And if this is the case, please let me know how you were following the docs to miss this step, and I can add it to another places in the docs you were looking at (where it's missing).

**Comment by radiantone** [comment]
I was able to load the module, and now trying to run redis server via singularity. The docs say 
```
$ singularity run <container>
```
Which I don't think is going to work

**Comment by vsoch** [comment]
What docs say `singularity run` anything? When you load redis you should have redis commands available to you- the point of shpc is to provide these easy wrappers instead of needing to assemble container interactions.

**Comment by vsoch** [comment]
Here is an example from my local install of shpc (alongside lmod). First note the module software can show me the commands available (note this is for lmod not TCL - you should have a similar command):

```bash
$ module show redis
```
```bash
 - redis-run:
       singularity run -B <moduleDir>/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container> "$@"
 - redis-shell:
       singularity shell -s /bin/sh -B <moduleDir>/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container>
 - redis-exec:
       singularity exec -B <moduleDir>/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container> "$@"
 - redis-inspect-runscript:
       singularity inspect -r <container>
 - redis-inspect-deffile:
       singularity inspect -d <container>
```
And these are the specific commands to hit executables inside the container (the defined aliases in the file)

```
 - redis-benchmark:
       singularity exec -B <moduleDir>/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container> /usr/local/bin/redis-benchmark "$@"
 - redis-check-aof:
       singularity exec -B <moduleDir>/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container> /usr/local/bin/redis-check-aof "$@"
 - redis-check-rdb:
       singularity exec -B <moduleDir>/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container> /usr/local/bin/redis-check-rdb "$@"
 - redis-cli:
       singularity exec -B <moduleDir>/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container> /usr/local/bin/redis-cli "$@"
 - redis-sentinel:
       singularity exec -B <moduleDir>/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container> /usr/local/bin/redis-sentinel "$@"
 - redis-server:
       singularity exec -B <moduleDir>/99-shpc.sh:/.singularity.d/env/99-shpc.sh <container> /usr/local/bin/redis-server "$@"
```
This means, for example, that if I want the functionality of `singularity run <container>` I would do redis-run. Let me know if you have any questions.

**Comment by radiantone** [comment]
Ok, I see now. Wasn't too clear for newbies from the web page. Thanks.

**Comment by vsoch** [comment]
@radiantone can you show me where your "entrypoint" to the docs was, and maybe we can add another snippet of text to make this more clear for the next person? Or if you want, you can open a PR and contribute a change to make them better! Your perspective as a new user is valuable and I want to make sure the docs aren't misleading or confusing given you haven't used shpc before.
