### ISSUE TITLE
Latest version is v0.0.5 when it should be v0.0.50

### ISSUE THREAD

**Issue by georgiastuart** [singularityhub/singularity-hpc#529]
Latest version is v0.0.5 when it should be v0.0.50. On pip it overwrote an old version of shpc instead of adding a new version. https://pypi.org/project/singularity-hpc/#history

**Comment by vsoch** [comment]
That's likely my fault - the way pypi works if I tried releasing a "0.0.50" it would truncate to 0.0.5" so we don't have much choice there! It's mostly my mistake releasing a version that is < 0.0.11.

**Comment by vsoch** [comment]
Oh huh actually I do see 0.0.30 - I'll try again today with 0.0.50. It might just be that 0.0.10 didn't work or something like that!

**Comment by vsoch** [comment]
okay just put in a test for this! https://github.com/singularityhub/singularity-hpc/releases/tag/0.0.50

**Comment by vsoch** [comment]
okay seems to be all set! Thanks for pointing this out - I've been missing it for several releases now!
