### ISSUE TITLE
shpc install not finding recipes

### ISSUE THREAD

**Issue by georgiastuart** [singularityhub/singularity-hpc#530]
**Describe the bug**

When I use `shpc install` to grab a recipe from https://singularityhub.github.io/singularity-hpc/, it returns `not a known recipe in any registry`. 

**To Reproduce**

```
$ shpc install biocontainers/samtools
biocontainers/samtools is not a known recipe in any registry.
```

**Expected behavior**
`biocontainers/samtools` is installed. 

**Version of Singularity and Singularity Registry HPC Client**

Singularity: v3.8.6
SHPC: v0.0.49

**Comment by georgiastuart** [comment]
So I think this might have to do with installing shpc in a conda environment possibly. I have

```
$ shpc config get registry
registry                       ['/home/georgia/.conda/envs/shpc/lib/python3.9/site-packages/registry']
```

as the default registry, which does not exist. Will investigate further.

**Comment by georgiastuart** [comment]
Ok I have more information:

### Case 1: `pip install singularity-hpc`

This results in the "not a known recipe" issue above. Registry points to 

```
registry                       ['/home/georgia/.conda/envs/shpc/lib/python3.9/site-packages/registry']
```

Which does not exist.

### Case 2: `pip install .` when pulled src from git

Same result as `Case 1`

### Case 3: `pip install -e .` when pulled src from git

This one works! The registry points to the in-source registry

```
registry                       ['/home/georgia/Projects/singularity-hpc/singularity-hpc/registry']
```

which exists and has the registry files. 

I think the fix is just in `setup.py` ensuring that the `registry` files get put in `site-packages` appropriately.

**Comment by vsoch** [comment]
@georgiastuart you are amazing! I just woke up and you've identified, tested, and fixed the issue! Thank you!!
