### ISSUE TITLE
Custom script wrappers

### ISSUE THREAD

**Issue by muffato** [singularityhub/singularity-hpc#546]
Hi @vsoch

I'm trying to define and use custom wrapper scripts, and I don't fully understand what shpc does, if that's expected, if there is a bug, etc.

My first question is about the template scripts that are added to the registry alongside the `container.yaml`, e.g. `singularity_fork.sh` in [vanessa/salad](https://github.com/singularityhub/singularity-hpc/blob/main/registry/vanessa/salad/container.yaml#L15-L20). The entry in the yaml only has the name of the alias/wrapper (e.g. `fork`) and the name of the template. In this case, it seems the template is expected to know which command to run inside the container. I've playing with that and only the `features.*` and `settings.*` variables seem to be present, not `alias.*`. Is that expected ?

Something else I find weird is https://github.com/singularityhub/singularity-hpc/blob/main/shpc/main/wrappers/base.py#L62-L105
- Line 71 it's checking the existence of the file in the current directory, which is unlikely to be a template directory. I believe the templates should only be looked in canonical locations (shpc's own templates dir, the one defined in the config file, or the registry alongside `container.yaml`). Is that a bug ?
- Line 83 it exits _before_ having checked the custom template directory (which is done line 94)
This seems to indicate that the custom template directory can effectively only be used for templates whose name exist in shpc's own template directory, i.e either `docker.sh` or `singularity.sh`, and nothing else.

The reason I'm asking is that I need to define alternative wrapper scripts for certain commands, and I although I could make them command-specific and put them in the registry, I would like to make them generic, understand the `alias.*` variables, and be stored in a more central location.
For instance, I wish https://github.com/singularityhub/singularity-hpc/blob/main/registry/vanessa/salad/container.yaml#L15-L20 could have an entry for `salad` to make it use an alternative template that would be interpolated with `alias.command=/code/salad`

Best,
Matthieu

**Comment by vsoch** [comment]
Did you see the documentation for wrapper scripts? We have for the developer user: https://singularity-hpc.readthedocs.io/en/latest/getting_started/developer-guide.html#wrapper-script and user: https://singularity-hpc.readthedocs.io/en/latest/getting_started/user-guide.html?highlight=wrapper#wrapper-scripts.

> My first question is about the template scripts that are added to the registry alongside the container.yaml

That's correct - there is no constraint or requirement about what you put. In this example, I show just running a command that isn't part of the container.yaml. However there are many variables available to you - the entire set in the table here: https://singularity-hpc.readthedocs.io/en/latest/getting_started/developer-guide.html#how-to-write-an-alias-wrapper-script. I don't expect writing them to be as easy as say, writing a container.yaml. It's sort of advanced functionaliy and the stronger use case is that someone wants all their scripts to be wrapper (so the alias commands better work in workflow managers, etc.) I'm surprised that alias isn't there, [it is passed to the template](https://github.com/singularityhub/singularity-hpc/blob/b2ea748d9e3280b8a60a08ae641f31106ec26f19/shpc/main/wrappers/base.py#L131).

> Line 71 it's checking the existence of the file in the current directory, which is unlikely to be a template directory. I believe the templates should only be looked in canonical locations (shpc's own templates dir, the one defined in the config file, or the registry alongside container.yaml). Is that a bug ?

[Line 71](https://github.com/singularityhub/singularity-hpc/blob/b2ea748d9e3280b8a60a08ae641f31106ec26f19/shpc/main/wrappers/base.py#L71) is actually just checking if a full path that already exists was provided. It would be valid for someone to define their own wrapper script in the settings or a container.yaml and just want to use it. After that we look in "expected places" like the container directory and wrapper script template directory. It is a not a bug - it let's a user define a wrapper script in some location outside the shpc install.

> Line 83 it exits before having checked the custom template directory (which is done line 94). This seems to indicate that the custom template directory can effectively only be used for templates whose name exist in shpc's own template directory, i.e either docker.sh or singularity.sh, and nothing else.

That is also correct (and warrants a comment). That section there is intended to find core templates (including the snippets) but not the file that is to be read in and rendered as the main file. E.g., [here](https://github.com/singularityhub/singularity-hpc/tree/main/shpc/main/wrappers/templates) is the main directory, and a user could write their own directory with "snippets" or similar to include.

> The reason I'm asking is that I need to define alternative wrapper scripts for certain commands, and I although I could make them command-specific and put them in the registry, I would like to make them generic, understand the alias.* variables, and be stored in a more central location.

Gotcha! So I do think alias should be there - it would probably be worth doing some bugging to see why what is getting passed is empty.

**Comment by muffato** [comment]
Thanks for the reply !

> Did you see the documentation for wrapper scripts? We have for the developer user: https://singularity-hpc.readthedocs.io/en/latest/getting_started/developer-guide.html#wrapper-script and user: https://singularity-hpc.readthedocs.io/en/latest/getting_started/user-guide.html?highlight=wrapper#wrapper-scripts.

Yes, I had read that, and I felt very confused because things didn't work as I was expecting - based on the documentation.

I get from the rest of your message that things mostly work as expected, except `alias.*` which should be there. I'll start a PR with a few code/documentation improvements, and we'll take it from there.

**Comment by vsoch** [comment]
Thank you @muffato !

**Comment by muffato** [comment]
And of course, despite having read the page https://singularity-hpc.readthedocs.io/en/latest/getting_started/developer-guide.html#wrapper-script multiple times, I only notice now that `alias` **is** there for container-level scripts too ! but as a _string_ rather than a _dictionary_ ... 🤦🏼

**Comment by muffato** [comment]
As I keep looking at the code for the wrapper scripts, what is the reason for forbidding template scripts from being named `podman.sh` ?

If one enters `podman.sh` in the [settings](https://github.com/singularityhub/singularity-hpc/blob/main/shpc/settings.yml#L73), shpc will [catch it](https://github.com/singularityhub/singularity-hpc/blob/main/shpc/main/wrappers/scripts.py#L14) and forcefully turn it to [`docker.sh`](https://github.com/singularityhub/singularity-hpc/blob/main/shpc/main/wrappers/scripts.py#L20).

**Comment by muffato** [comment]
Q. What do you think of shpc using `singularity.sh` / `docker.sh` from the container directory (if present), _without_ having to declare anything in `container.yaml` ? In other words, and without having to use the `singularity_scripts:` and `docker_scripts:` sections, shpc would first look for said templates in the container directory, and then in the global template directory.

**Comment by vsoch** [comment]
I think it’s better to have them explicitly defined so the user can name them whatever they like, have more than one, and we don’t search if not defined.

**Comment by vsoch** [comment]
@muffato anything else for discussion here?

**Comment by muffato** [comment]
I think it's all good now that the PR has been accepted, and this could be closed ?
