### ISSUE TITLE
Missing features/gpu: true in many nvidia containers

### ISSUE THREAD

**Issue by surak** [singularityhub/singularity-hpc#570]
**Describe the bug**

A number of NVIDIA containers from NVCR.IO simply lack the "features:gpu" tag, so they won't see multi-gpus.

I would expect all NVIDIA-optimized codes to use gpus :-)

For example:
https://github.com/singularityhub/singularity-hpc/blob/main/registry/nvcr.io/nvidia/rapidsai/rapidsai/container.yaml
https://github.com/singularityhub/singularity-hpc/blob/main/registry/nvcr.io/nvidia/hpc-benchmarks/container.yaml
https://github.com/singularityhub/singularity-hpc/blob/main/registry/nvcr.io/nvidia/digits/container.yaml
https://github.com/singularityhub/singularity-hpc/blob/main/registry/nvcr.io/nvidia/tensorflow/container.yaml

**Comment by vsoch** [comment]
This was merged (and I forgot to close) thanks @surak !
