### ISSUE TITLE
Directory structure in the registry

### ISSUE THREAD

**Issue by muffato** [singularityhub/singularity-hpc#578]
Hi @vsoch 

A question about the nomenclature for organising container.yaml files in the registry. It looks like the current guideline is to follow the path one would give to `docker pull`, i.e.:
 - docker hub "library" images can go straight at the top, e.g. `mariadb`
 - per-user/org docker images go into the user/org directory, e.g. `vanessa/salad`
 - another directory can be used on top for alternative docker servers, e.g. `ghcr.io/autamus/abyss`

Is this a guideline or a requirement ? We're considering moving the docker-hub based images to their own directory, so that the top-level would be ghcr.io, quay.io, our gitlab, and docker, and we're wondering if that would break something.

**Comment by vsoch** [comment]
It’s a requirement that the organization matches the naming, yes. I think you could test not adhering to it but likely you’d hit bugs.

**Comment by muffato** [comment]
Intriguing: having `container.yaml` under `docker.io/hashicorp/vault` works – but `docker.io` is a valid name for the docker server anyway.

`awesomedocker/hashicorp/vault` works too, although there is a discrepancy between what’s displayed and the actual path
```
$ shpc install awesomedocker/hashicorp/vault
(...)
Module awesomedocker/hashicorp/vault:1.11.0 was created.
$ tree modules/
docker.io/
└── hashicorp
    └── vault
```

**Comment by vsoch** [comment]
@muffato any more to discuss here? Ironically for the shpc-guts https://github.com/singularityhub/shpc-guts repository I require the registry, so we don't have this discrepancy. Is this something we should do here (at risk of course of borking everyone's module namespace?)

**Comment by muffato** [comment]
I think the conclusion was that for Docker, containers can be put either at the root, or under `docker.io/` since these are synonyms. I haven't tried the other container registries, but I expect they may indeed fail if declared under the wrong namespace.

**Comment by vsoch** [comment]
Indeed they would! Docker.io is sort of the default namespace, as a way to think about it. If you don't think we should change this organization, feel free to close the issue.
