### ISSUE TITLE
Customise container naming

### ISSUE THREAD

**Issue by audreystott** [singularityhub/singularity-hpc#598]
**Is your feature request related to a problem? Please describe.**
No, but it would remove the blocker for using currently available containers

**Describe the solution you'd like**
To be able to customise the naming convention for the singularity pull

E.g. fastqc v0.11.9 is pulled as:
```~/quay.io/biocontainers/fastqc/0.11.9--0/quay.io-biocontainers-fastqc-0.11.9--0-sha256:319b8d4eca0fc0367d192941f221f7fcd29a6b96996c63cbf8931dbb66e53348.sif```

But if the naming can be customised, it would ideally be:
```~/f/a/fastqc:0.11.9--hdfd78af_1```

This is because we have an entire biocontainers Singularity containers repo (http://datacache.galaxyproject.org/singularity/) that is read-only and that we would like to use as our containers base.

**Describe alternatives you've considered**
Possibly, scripting to divert SHPC to check for `~/f/a/fastqc:0.11.9--hdfd78af_1` if `~/quay.io/biocontainers/fastqc/0.11.9--0/quay.io-biocontainers-fastqc-0.11.9--0-sha256:319b8d4eca0fc0367d192941f221f7fcd29a6b96996c63cbf8931dbb66e53348.sif` cannot be found

**Comment by vsoch** [comment]
Have you tried installing to a view? https://singularity-hpc.readthedocs.io/en/latest/getting_started/user-guide.html#installing-modules-to-a-view The names are automatically shortened.

Also my browser doesn't let me see your galaxy page:

![image](https://user-images.githubusercontent.com/814322/195491026-4cce3306-b75c-4462-91fe-954d1a276fca.png)

so if you could write out what you are wanting for your containers, it would help me to understand! If they aren't added to shpc, we have automation means to do that (and I could certainly help!)

**Comment by audreystott** [comment]
Thanks Vanessa. 

I wasn't aware of shpc view but it looks like something we can certainly use but only after we cross the hurdle of the naming I think.

So the link I sent you is just an entire repository with biocontainers singularity containers on there. To be able to use those containers, I would like to get SHPC to see them as being present. They are all under a read-only directory `/cvmfs/singularity.galaxyproject.org`.

So for example, fastqc (version 0.11.9) are here:
```
$ ls -lh /cvmfs/singularity.galaxyproject.org/all/fastqc:0.11.9*
-rw-r--r-- 1 cvmfs cvmfs 253M Jan 25  2020 /cvmfs/singularity.galaxyproject.org/all/fastqc:0.11.9--0
-rw-r--r-- 1 cvmfs cvmfs 272M Mar 25  2021 /cvmfs/singularity.galaxyproject.org/all/fastqc:0.11.9--hdfd78af_1
```

They are all actually sif files, so there's no need for Singularity to pull them down. Only for SHPC to recognise them and use them. Is there a way for the recipe file to be written such that when I do an `shpc install fastqc`, it would create the module but not pull the container?

**Comment by vsoch** [comment]
Yes, we have a command for that too! You'll want to do shpc add https://singularity-hpc.readthedocs.io/en/latest/getting_started/user-guide.html#add-a-local-container and then shpc install - so you can control the namespace (and ultimately install to a view if you like, which is a symlink from a main install). Note that a part of that is making a filesystem registry, as the default installs from our shpc-registry on GitHub. https://singularity-hpc.readthedocs.io/en/latest/getting_started/user-guide.html#creating-a-local-registry.

**Comment by audreystott** [comment]
Ah that's nice!

So I was able to create the registry and add the container. But could not install it as it tries to create a path that is a read-only directory. This is where I was concerned, because our containers are all in a read-only directory. If we could get SHPC to write `/cvmfs/singularity.galaxyproject.org/all/blast:2.9.0--pl526he19e7b1_7` where it is a colon `:` after `blast` instead of a slash `/`, that might work.

```
$ shpc add /cvmfs/singularity.galaxyproject.org/all/blast:2.9.0--pl526he19e7b1_7 blast:2.9.0--pl526he19e7b1_7 --registry all
Registry entry blast was added! Before shpc install, edit:
all/blast/container.yaml
$ shpc install all/blast:2.9.0--pl526he19e7b1_7
Error creating path /cvmfs/singularity.galaxyproject.org/all/blast/2.9.0--pl526he19e7b1_7, exiting.
```

Thoughts?

**Comment by vsoch** [comment]
@audreystott yes we could definitely support that! I'll need to add a flag in the user settings to control it, which I can do tomorrow.

**Comment by vsoch** [comment]
Or @audreystott what if we just didn't move the container from where it originally is?

**Comment by muffato** [comment]
I was not aware of this CernVM-FS for biocontainers. That's really cool !
I really like the principle of this idea, especially as the containers my team manages largely overlap other teams in the institute, and many containers have other copies for say Nextflow and other reasons. It'd be great if we could have just one copy of each.

Could we perhaps consider a command-line option in `shpc install` to provide the path of an existing Singularity image to use directly ? shpc could compare the checksums in order to make sure the image is what it expects, and then use it. `container.yaml` wouldn't have to be edited

**Comment by vsoch** [comment]
> Could we perhaps consider a command-line option in shpc install to provide the path of an existing Singularity image to use directly ? shpc could compare the checksums in order to make sure the image is what it expects, and then use it. container.yaml wouldn't have to be edited

I'm not sure I totally understand this use case - we need the container.yaml to define metadata (aside from the digest) like the entrypoints, and ensure that the module generated has those that are needed. We already have a command to generate a container.yaml for an existing SIF, and that is what is needed here.

**Comment by muffato** [comment]
The discussion was going towards: "the containers are there, great, let's just use `shpc add` to use them, but you'll have to fill in the aliases in container.yaml"
I think making local registries goes against a principle of shpc. Sharing those container.yaml and depositing them into the shpc-registry repository wouldn't be as straightforward if they point to local sif files.

This is why, I'd be looking for a solution that preserves the existing container.yaml, but asking shpc to peek into an existing cache (or call it library).

**Comment by vsoch** [comment]
>  Sharing those container.yaml and depositing them into the shpc-registry repository wouldn't be as straightforward if they point to local sif files.

Is there absolutely no record of how these containers were generated? And they aren't in a registry? How did they get there? :thinking: 

> This is why, I'd be looking for a solution that preserves the existing container.yaml, 

What container.yaml are we talking about if we haven't generated any? 

> but asking shpc to peek into an existing cache (or call it library).

So we'd check a digest of a container against an entire repository of them? I think in practice the hash of a SIF won't == the hash of the docker digest - there are a lot of details (uncompressed, manifests, etc) that we don't know.

**Comment by vsoch** [comment]
If you are wanting "turn this entire folder of SIF files into a module install, with no customization or aliases" I guess we could do that, but it would only provide run/shell/exec commands and nothing specific. We'd need another tool that, akin to the action, can "discover" meaningful entrypoints.

**Comment by muffato** [comment]
Let's say I've got this CernVM-FS on my cluster, and I want to install software from the official shpc registry, e.g. [samtools:1.15--h3843a85_0](https://github.com/singularityhub/shpc-registry/blob/main/quay.io/biocontainers/samtools/container.yaml#L13). samtools is already there on the filesystem, at [`/cvmfs/singularity/s/a/samtools:1.15--h3843a85_0`](http://datacache.galaxyproject.org/singularity/s/a/samtools%3A1.15--h3843a85_0). It'd be great if I could tell shpc: install the software as per the upstream container.yaml, but use this existing .sif instead of pulling one again.
No need to modify any container.yaml, no need to maintain an alternative registry, but the onus is onto the user to know which .sif from the cache corresponds to which shpc software/tag.

**Comment by vsoch** [comment]
ohhh I get it! So you want to match an existing registry container.yaml to the local SIF. Yes I like that idea a lot!

In practice, how much overlap do we have?

**Comment by muffato** [comment]
Overlap between the containers used in the shpc registry and this cvmfs server ? I think they have all of conda-forge and bioconda channels

**Comment by vsoch** [comment]
okay I think I'm following now! I'll try to do a PR with this feature either later today (still ~6am) or this week.

**Comment by muffato** [comment]
(no rush on my side. maybe wait for @audreystott to comment ? I may be pushing you in a different direction from what she'd like)

**Comment by vsoch** [comment]
@muffato it was fairly easy to implement (and I really like the idea!) so I opened a PR for it anyway - and we can still wait for @audreystott to continue discussion about this particular use case. https://github.com/singularityhub/singularity-hpc/pull/602.

I think likely we will want something like this regardless - the idea of "I have all these images that I can match to some registry metadata and would like to install as such" makes a lot of sense.

**Comment by audreystott** [comment]
Thanks @vsoch and @muffato for furthering the discussions. Yes absolutely this is the direction I was looking at, i.e. we need shpc to make these container.yaml files but match the existing sif files that are on the cvmfs server. Note that in this cvmfs server, the sif files don't have the extension `.sif` or the SHA number following it. 

(BTW @muffato we have exactly the same reason - containers being used by different groups/labs that can be shared. the Galaxy Project have multiple Stratum1 servers around the world - https://galaxyproject.org/admin/reference-data-repo/#cvmfs-server-details - so you can select the one closest to you and make a proxy to cache from it.)

**Comment by vsoch** [comment]
@audreystott the link you first shared doesn't work for me, but if you could share an entire list of containers there, I could:

1. ensure there is a match in our registry
2. prepare a little script to install the SIFs !

**Comment by audreystott** [comment]
@vsoch there are hundreds possibly over a thousand sif files there. I haven't actually done a line count. I wasn't expecting that you would add the registry for me. (If there was a match, I would still need shpc to use the containers on there). How about this link - https://depot.galaxyproject.org/singularity/

**Comment by vsoch** [comment]
Yes, that one works, thank you! There are indeed a LOT so what I'll likely do is a chunk of them when I have free time, and working toward a good set - and actually I might be able to automate some given that list! Do you know if there is a process (aside from looking at that URL) for adding new containers that I could plug into?

**Comment by audreystott** [comment]
Awesome, thank you so much. Automation would be awesome. As this server is maintained by the Galaxy Project, I do not know their process for adding new containers on there. I could potentially find out if that is something you would like to add to the automation for future containers?

**Comment by vsoch** [comment]
That would be hugely useful, yes! What I'll primarily be doing now is looking for a container match based on name - but if they have a GitHub repository somewhere where they build -> deploy the containers (and I can see the registry URIs exactly) we could maintain a fairly nice match between the two.

**Comment by vsoch** [comment]
okay I think I got the hang of this!

![image](https://user-images.githubusercontent.com/814322/196079404-4d2f168f-7398-4b4f-a3c8-53a75b36ea40.png)

I'm kind of pooped now, but if I keep adding these as a background task during other work, we will eventually get most of them! And then I can do a rough matching. After that I'll want to know how these are deployed and then maybe we can automate the whole thing. It will be a bit of work up front, but worth it I think.

**Comment by audreystott** [comment]
You're an absolute champ. I found this `singularity_build.sh` script on their depot page: https://depot.galaxyproject.org/singularity/bin/ which details the singularity pull from quay.io/biocontainers. Looks like initially that's what they did. There are over 20k containers. Insane! But I will keep asking/finding out what their process might be for new versions/containers, as I can see on the depot page that they have new uploads.

**Comment by vsoch** [comment]
Thank you! I’ll keep you updated with my progress, maybe at the end of each week. A lot of the container files are just different tags (and they are based on commit so one repo can easily have 50-100) so I don’t expect to actually be creating that many registry entries!

**Comment by audreystott** [comment]
Ok so it looks like the automation of new containers is further up the chain, with biocontainers. When a biconda recipe is created, the Conda package can be built, which automatically triggers bio containers to build a docker container. At the same time, singularity contaers are also automatically pulled into different registries, including the galaxyproject one. https://pubs.acs.org/doi/10.1021/acs.jproteome.0c00904, under `BioContainers Infrastructure`.

Is there anything I can do to help with that? I would be more than happy to share the load.

**Comment by audreystott** [comment]
PS: I just realised I will be meeting with the Biocontainers people at some point soon - meeting is currently being organised by our project partner. Will keep you in the loop when I know more!

**Comment by vsoch** [comment]
Oh, fantastic! And I’ll poke around their repos / automation to see what I can find this week. Since we only need a Docker registry URI, a URL and a description, I am optimistic we can figure something out. Thanks @audreystott!

**Comment by vsoch** [comment]
okay I actually was able to write a script to automate generation! 

![image](https://user-images.githubusercontent.com/814322/196092843-3ade96d3-07d2-4bb4-ac89-a5ee92d63439.png)

It parses their listing of containers, and based on the script you showed me, I can see they just add `quay.io/biocontainers` as a prefix to get the container! The tags they provide there aren't actually correct, so I add in another API call to retrieve actual current tags from the registry (in the image above).

Barring the API endpoints don't hit a ratelimit, I should at least be able to start generating the container.yaml files - after getting the tags, and [using pipelib to sort to latest](https://vsoch.github.io/pipelib/getting_started/user-guide.html#a-real-world-example-docker-tags) and grabbing the latest as the example for the shpc-guts to derive the container.yaml, the limitation in the beginning will just be my computer pulling images to get the entrypoints for the container.yaml, and then the next work intensive step is cleaning up the executables in those files (probably not required but good to do). I still haven't convinced myself it's too much to do :) I suppose I like redundant tasks like that! :laughing: 

Anyhoo, will keep you updated! Going to bed soon for sure.

**Comment by vsoch** [comment]
Oh and I almost forgot! After this initial run, I'll add the update script to shpc-registry, so we will do the same (but since changes will be incremental the PRs with updates will be much easier to handle).

**Comment by audreystott** [comment]
Fantastic work. Yes not a rush as we are currently doing testing stuff atm. But have plans for next year to implement SHPC as our containers module across a few infrastructures in Australia!

**Comment by vsoch** [comment]
@audreystott for one more update for my plan - generating the container.yaml files (without aliases) is really easy, but I think we can try to do better - I started generating container.yaml with aliases manually (realized this wouldn't scale) and then I added to the script to extract the aliases, but they wouldn't be high quality if we just include everything (there is a lot of extra stuff typically installed to /usr/local/bin we wouldn't want to include, it's noise). So what I'm going to do is extract aliases in /usr/local/bin across containers, and then I'll find meaningful ones by some filter for frequency (TBA!) For the time being I'm just generating the commands (which might be useful to someone else eventually anyway). I'm up to b's woot! 

https://github.com/singularityhub/shpc-registry-cache

**Comment by vsoch** [comment]
Update on speed: it's about 1/8 done (out of 8k unique containers) after a day, so this will likely be done in 1-2 weeks (giving some extra padding for the time I'll take to finalize the algorithm to derive important tags and generate the container.yaml files).

**Comment by audreystott** [comment]
Wow!! That is impressive. Looking forward to the container.yaml files!

**Comment by vsoch** [comment]
Okay phew! So the parsing is done, I have a shpc-registry-cache now (that will auto update with new entries, and get tags / counts for aliases for later use) and then some automation in progress to use that to derive new container.yaml (with aliases) for shpc-registry! See the notes here: https://github.com/singularityhub/shpc-registry/pull/26 we can't merge until I've also added a new updating strategy. So - not done yet, but making progress!

**Comment by audreystott** [comment]
That went faster than expected. Getting closer. Thanks for the update!

**Comment by audreystott** [comment]
Will the paths generated on the module files depend on the way the tags are written in the container.yaml files? If so, we would have to write the container.yaml files such that the hash is not included. Also with the way the paths are written in the cvmfs repo, all the containers are pretty much dumped under the `/cvmfs/singularity.galaxyproject/all/` directory. So that the path in the module files would reflect the same.

**Comment by audreystott** [comment]
E.g. for the above:
```
$ ls /cvmfs/singularity.galaxyproject.org/all/fastqc
fastqc-rs:0.1.0--h374f2b1_0  fastqc-rs:0.3.2--he9f29cb_1  fastqc:0.11.5--pl5.22.0_2    fastqc:0.11.7--pl5.22.0_1
fastqc-rs:0.2.0--h374f2b1_0  fastqc:0.10.1--1             fastqc:0.11.5--pl5.22.0_3    fastqc:0.11.7--pl5.22.0_2
fastqc-rs:0.2.1--h374f2b1_0  fastqc:0.11.2--1             fastqc:0.11.6--2             fastqc:0.11.8--0
fastqc-rs:0.2.1--had16127_1  fastqc:0.11.2--pl5.22.0_0    fastqc:0.11.6--pl5.22.0_0    fastqc:0.11.8--1
fastqc-rs:0.2.1--had16127_2  fastqc:0.11.3--0             fastqc:0.11.6--pl5.22.0_1    fastqc:0.11.8--2
fastqc-rs:0.2.2--had16127_0  fastqc:0.11.3--1             fastqc:0.11.7--4             fastqc:0.11.9--0
fastqc-rs:0.3.0--hb7f7c69_0  fastqc:0.11.4--1             fastqc:0.11.7--5             fastqc:0.11.9--hdfd78af_1
fastqc-rs:0.3.1--hb7f7c69_0  fastqc:0.11.5--1             fastqc:0.11.7--6             
fastqc-rs:0.3.1--he9f29cb_1  fastqc:0.11.5--4             fastqc:0.11.7--hdfd78af_7    
fastqc-rs:0.3.2--he9f29cb_0  fastqc:0.11.5--hdfd78af_5    fastqc:0.11.7--pl5.22.0_0 
```

**Comment by vsoch** [comment]
You’d need to create a view to discard the tags, but you can’t arbitrarily rename tags (to one’s that don’t exist).

**Comment by audreystott** [comment]
Hmm ok. So we don't actually need to worry about the hash if the path is amended from:
```
latest:
  0.11.9--0: sha256:56303eba371672d61c9a497702c207e4e47a9c8766d1edc3d9d75351f00332f5
tags:
  0.11.9--0: sha256:56303eba371672d61c9a497702c207e4e47a9c8766d1edc3d9d75351f00332f5
path: sha256:56303eba371672d61c9a497702c207e4e47a9c8766d1edc3d9d75351f00332f5.sif
``` 
to be:
```
  0.11.9--0: sha256:56303eba371672d61c9a497702c207e4e47a9c8766d1edc3d9d75351f00332f5
tags:
  0.11.9--0: sha256:56303eba371672d61c9a497702c207e4e47a9c8766d1edc3d9d75351f00332f5
path: /cvmfs/singularity.galaxyproject.org/all/fastqc
```
But we still have a blocker:
```
$ shpc install all/fastqc
Error creating path /cvmfs/singularity.galaxyproject.org/all/fastqc/0.11.9--0, exiting.
```
because the container path is:
`/cvmfs/singularity.galaxyproject.org/all/fastqc:0.11.9--0`
(noting the `:` instead of the `/` before the tag number).

**Comment by vsoch** [comment]
You are missing a step we developed for you to install an existing container.

**Comment by vsoch** [comment]
To keep you in the loop, this is an example of the new workflow that does updates incrementally - https://github.com/singularityhub/shpc-registry/pull/30/files. That will be important when there are 8K plus! That uses this action I put together last night: https://github.com/vsoch/split-list-action. I'm going to let it run a few days to make sure it works as I expect, and then I'll hold my breath and merge in the 8k new ones. If you want to take a look at that PR and do some spot checks for the executables in the meantime that would be very helpful!

(Don't worry about the conflcits - that is to be expected since I updated the workflow / readme and I'll fix before merging!) https://github.com/singularityhub/shpc-registry/pull/26

**Comment by vsoch** [comment]
okay - here is a script for you to test out! Please use `--dry-run` first! Put any requests for tweaks directly in the PR (comments or suggestions): https://github.com/singularityhub/singularity-hpc/pull/613 gnite!

**Comment by audreystott** [comment]
Executables for the two biocontainers gatk4 and diamond in the subset are correct, i.e. `gatk` for `gatk4` and `diamond` for `diamond` are the only executables for each of the containers

**Comment by vsoch** [comment]
@audreystott I think we are good to close here? The solution we arrived at was the custom install script for the biocontainers I think?

**Comment by audreystott** [comment]
Yes please feel free to close. We got the solution from the install script. Thanks!
