### ISSUE TITLE
Best way to load the Singularity module automatically?

### ISSUE THREAD

**Issue by georgiastuart** [singularityhub/singularity-hpc#599]
On my systems, `singularity` is behind an lmod module and not loaded by default. I'm trying to figure out the best way to inject `load("singularity")` into the modulefile generated by shpc. It's not really a view since it needs to happen for every container. How would you recommend going about this?

**Comment by georgiastuart** [comment]
I may just patch it in to the modulefile template in our install RPM, but that's a bit extreme.

**Comment by vsoch** [comment]
Why not use a view and add to system_modules?

**Comment by georgiastuart** [comment]
@vsoch if I set the default view as an admin, will that propagate to all users?

**Comment by vsoch** [comment]
@georgiastuart a view is just another module folder (with symlinks instead of files) so if you have this added to module load (or similar, however you expose modules to users) they should be able to access. That said, I've never personally tried that out because I don't run a cluster! Pinging @marcodelapierre in case he has.

**Comment by georgiastuart** [comment]
Ah, I think I understand now. The default view is just for installation so that's fine, and then we can just add the appropriate path to `$MODULEPATH`. 

However, I added the module and it's still not being loaded. Not sure why.

**Comment by georgiastuart** [comment]
I've got a hunch for why it's not working. Seeing if I can fix it and then will submit a PR for y'all to check out.

**Comment by georgiastuart** [comment]
Closed with #600 !

**Comment by vsoch** [comment]
Holy cow number 600!! That is some kind of milestone I think! :trophy:

**Comment by marcodelapierre** [comment]
Hi @georgiastuart , sorry I had missed this one!


You can also achieve pre-loading singularity by means of a setting in `settings.yml`:
```
singularity_module: 
```
