### ISSUE TITLE
shpc uninstall and tool versions

### ISSUE THREAD

**Issue by muffato** [singularityhub/singularity-hpc#601]
**Describe the bug**

`shpc uninstall $tool` actually only deletes the latest tag of that tool, not the other tags, while letting the user think all tags are deleted.
`shpc uninstall $tool:$version` requires the tag to still be present in the registry.
 
**To Reproduce**
```
$ shpc list
quay.io/biocontainers/samtools:1.13--h8c37831_1
quay.io/biocontainers/samtools:1.15--h3843a85_0
quay.io/biocontainers/samtools:1.14--hb421002_0

$ shpc uninstall quay.io/biocontainers/samtools
Are you sure you want to uninstall quay.io/biocontainers/samtools? (yes/no)? y
$container_base/quay.io/biocontainers/samtools and all subdirectories have been removed.
$module_base/quay.io/biocontainers/samtools and all subdirectories have been removed.

$ shpc list
quay.io/biocontainers/samtools:1.13--h8c37831_1
quay.io/biocontainers/samtools:1.14--hb421002_0
```

I also noticed that `shpc uninstall` requires the version to be present in the registry to accept it. In the example above the true version in the registry is `1.13--h8c37831_0` (ending with 0), and I've locally renamed the installed module to `1.13--h8c37831_1` to mimic an outdated version one that one may want to uninstall. `shpc uninstall` doesn't let me remove it
```
$ shpc uninstall quay.io/biocontainers/samtools:1.13--h8c37831_1
quay.io/biocontainers/samtools is not a known identifier. Choices are:
1.10--h2e538c0_3
1.11--h6270b1f_0
1.12--h9aed4be_1
1.13--h8c37831_0
1.14--hb421002_0
1.15--h3843a85_0
```

**Expected behavior**

I would expect `shpc uninstall $tool:$version` to remove a particular version (regardless of what the registry knows about it) and `shpc uninstall $tool` to remove all versions currently installed.

**Version of Singularity and Singularity Registry HPC Client**

I'm on 6b553c92884e9ef450f01353e4797ea7f7e5f147

I'm happy to fix that if you agree with the intended behaviour.

**Comment by vsoch** [comment]
Ah indeed! This looks like a bug - I'm fairly sure this worked before so I think we probably broke with recent changes!

>  I'm happy to fix that if you agree with the intended behaviour.

Would love that, if you have the bandwidth! It might be good to throw in a quick test this time so we don't break it again :laughing:
