### ISSUE TITLE
Option to pull by tag and not by sha

### ISSUE THREAD

**Issue by georgiastuart** [singularityhub/singularity-hpc#604]
**Is your feature request related to a problem? Please describe.**

My institution runs a self-hosted docker registry that appears not to cooperate with SHA-based pulls. 

**Describe the solution you'd like**

I'd like the option to pull by tag and not by sha, e.g.,

```bash
shpc config set pull_method "tag"
shpc config set pull_method "sha"
```

**Describe alternatives you've considered**

For our install RPM, I've patched it to pull by tag but it's hacky. I'm happy to try to implement in a better way!

**Comment by vsoch** [comment]
Can you give me mode details about this registry? Most registry with tags have sha under the hood - a tag is just a reference to a digest, so I'm curious why this doesn't work!

**Comment by georgiastuart** [comment]
Yeah I'm confused too! It's just `docker-registry` v2.7.1 installed from apt on Debian 11 (bullseye). Appears to be a 2019 release.

**Comment by vsoch** [comment]
Sounds good! If you can give me pull commands that work we can try to debug what is going on.

**Comment by georgiastuart** [comment]
Well, it appears to be functioning now without issue. I did make some changes (set up a nginx proxy, etc) between when I was getting errors complaining about pulling with the digest and now so I wonder what fixed it. 

I'm going to close this issue since it seems like it was a computer gremlin situation :)

**Comment by vsoch** [comment]
ah, the gremlins are back!! :japanese_goblin: :zombie:
