### ISSUE TITLE
invalid command shpc config edit

### ISSUE THREAD

**Issue by shahzebsiddiqui** [singularityhub/singularity-hpc#619]
In https://singularity-hpc.readthedocs.io/en/latest/getting_started/installation.html there is a command `shpc config edit` 
![Screen Shot 2022-11-28 at 6 38 40 PM](https://user-images.githubusercontent.com/12942230/204403411-9aeec346-8bce-46e7-be14-58eeab90be26.png)

I tried this and got an error, it looks like its not a registered command

```
(singularity-hpc)  ~/singularity-hpc/ [main] shpc config edit
Singularity is not installed, functionality might be limited.
edit is not a recognized command.
```

Note i am using the devel of this repo

**Comment by shahzebsiddiqui** [comment]
okay never mind i got this working now it was an old version after updating to latest version this command was working.

**Comment by vsoch** [comment]
Yep :)
