### ISSUE TITLE
Cleanup old branches

### ISSUE THREAD

**Issue by muffato** [singularityhub/singularity-hpc#635]
Hi @vsoch 
Could you perhaps cleanup old branches that have since been merged or closed ?

I can recognise these ones
- origin/add/symlink-install
- origin/remove-symlink-install
- origin/remove-custom-loader
- origin/allow/custom-includes
- origin/tcl_default_version
- origin/symlink-redo
- origin/add/symlink-instal
- origin/remove-tcl-extension

and a whole lot binoc updates

**Comment by vsoch** [comment]
All set.

**Comment by muffato** [comment]
Thank you !
