### ISSUE TITLE
Lmod being populated with a bunch of executables when using default module setup

### ISSUE THREAD

**Issue by georgiastuart** [singularityhub/singularity-hpc#637]
**Describe the bug**

When I run something like `shpc install python` with the default setup, my `lmod` output looks like this:

```
----------------------------------- /home/georgia/Projects/foss/singularity-hpc/modules ------------------------------------
   python/3.10/99-shpc.sh              python/3.10/bin/python-inspect-deffile      python/3.10/bin/python-shell
   python/3.10/bin/python-container    python/3.10/bin/python-inspect-runscript    python/3.10/bin/python       (D)
   python/3.10/bin/python-exec         python/3.10/bin/python-run                  python/3.10/module
```

I would not expect all the executables to populate lmod. I'm not sure if this is an issue with my lmod config (default Ubuntu apt install, version 6.6) or SHPC. Any suggestions?

**To Reproduce**

Ubuntu 22.04LTS. 

1. Install lmod with `apt-get install lmod`
2. Install SHPC in a conda environment
3. Add SHPC default module folder to `MODULEPATH`
4. `shpc install python:3.10`
5. Examine `module avail`

**Expected behavior**
I think it should be something like

```
----------------------------------- /home/georgia/Projects/foss/singularity-hpc/modules ------------------------------------
python/3.10/module
```

**Version of Singularity and Singularity Registry HPC Client**
Current `main` of shpc. Lmod 6.6

**Comment by marcodelapierre** [comment]
is this the latest SHPC version Georgia?

**Comment by vsoch** [comment]
Sorry I didn't see this earlier! I'm testing in a container, and not able to reproduce. 

![image](https://user-images.githubusercontent.com/814322/229422351-81d3125c-01dc-4232-be0e-a0409adb9d51.png)

Here is my Dockerfile - note that the lmod from apt didn't seem to let me run module load, so I installed from conda.

```dockerfile
FROM continuumio/miniconda3

RUN pip install singularity-hpc
ENV MODULEPATH=/opt/conda/lib/python3.10/site-packages/modules

RUN  conda install -c conda-forge singularity && \
     conda install -c conda-forge lmod && \
     shpc install python:3.10
```
Build

```dockerfile
$ docker build -t test .
```
And then run the module avail

```bash
$ docker run -it test
$ module avail
```
```console
--------------- /opt/conda/lib/python3.10/site-packages/modules ----------------
   python/3.10/module

-------------------- /opt/conda/lmod/lmod/modulefiles/Core ---------------------
   lmod    settarg

Module defaults are chosen based on Find First Rules due to Name/Version/Version modules found in the module tree.
See https://lmod.readthedocs.io/en/latest/060_locating.html for details.

If the avail list is too long consider trying:

"module --default avail" or "ml -d av" to just list the default modules.
"module overview" or "ml ov" to display the number of modules for each name.

Use "module spider" to find all possible modules and extensions.
Use "module keyword key1 key2 ..." to search for all possible modules matching
any of the "keys".
```

So - possibly something about the lmod version from apt? Or the config for it? Or using explicitly a conda environment (I installed directly to the base environment).

**Comment by georgiastuart** [comment]
Thanks! I tried with installing `lmod` in a conda environment and it worked as intended. I think the lmod in apt is just too out of date. 

Closing this because it appears to be an lmod version issue and not a shpc issue.
