### ISSUE TITLE
limit output of shpc show

### ISSUE THREAD

**Issue by shahzebsiddiqui** [singularityhub/singularity-hpc#646]
**Is your feature request related to a problem? Please describe.**
This issue is motived by https://github.com/singularityhub/singularity-hpc/issues/645 where we can limit the query of number of containers when running `shpc show` instead of having it show all containers

**Describe the solution you'd like**

Perhaps consider an option `shpc show --count=X` where `--count` can limit number of entries that are queried. There could be a short option perhaps `-c`

**Describe alternatives you've considered**

I tried running `shpc show | head -n X` to get around this but its not perfect.

**Comment by vsoch** [comment]
Just curious, what's the use case for a limited set? I would assume if someone wants to see a smaller set they would use `--filter` to select a set of interest. I'm not sure why just a smaller set (of the first random N) would be wanted, but I'm interested to know!

**Comment by vsoch** [comment]
Please see https://github.com/singularityhub/singularity-hpc/pull/647

**Comment by shahzebsiddiqui** [comment]
thanks for adding this. I was actually trying to do a `shpc show | head -n X` to see top X lines of the code and i realize there could be a better way to do this using an option. My use-case was to do a screenshot of `shpc show`. I was working on a slide deck to present internally on this tool. But yeah i like this feature. Thanks for adding this!
