### ISSUE TITLE
Install with version number but without build string

### ISSUE THREAD

**Issue by mdehollander** [singularityhub/singularity-hpc#651]
**Is your feature request related to a problem? Please describe.**
Not sure if this a recommended way of working, but would it be possible to install containers with a version but without the build string

**Describe the solution you'd like**
I would like that the below command would work, but now it suggest versions with build numbers
```
$ shpc install fastp:0.22.0
quay.io/biocontainers/fastp:0.22.0 is not a known identifier. Valid tags are:
0.22.0--h2e03b76_0
0.23.2--h5f740d0_3
0.23.4--h5f740d0_0
```
**Describe alternatives you've considered**
Installing fastp (with an active namespace) with version and build string works:
```
$ shpc install fastp:0.23.4--h5f740d0_0
Module quay.io/biocontainers/fastp:0.23.4--h5f740d0_0 was created.
```

**Comment by vsoch** [comment]
Hi @mdehollander! You are installing a container tag, and not explicitly a version number. Those are the format that are provided by biocontainers - not pretty by any means. To install you need to choose a version (one of the tags shown).

**Comment by mdehollander** [comment]
Ok! :+1: Thanks for the clarification.
