### ISSUE TITLE
wrapper_base environment variable not expanded

### ISSUE THREAD

**Issue by theklaloizou** [singularityhub/singularity-hpc#659]
After the addition of wrapper_base option in settings.yml file we noticed that when we use an environment variable in the wrapper_base path the variable is not expanded correctly. Note that we are running shpc install from inside a singularity container.

So if we have:
wrapper_base: $SHPC_ROOT/wrappers

it is not working while if we set the full path it is:

wrapper_base: /data/shpc/wrappers

This can be fixed by adding the wrapper_base in the allowed_envars in defaults.py file:

# variables in settings that allow environment variable expansion
allowed_envars = ["container_base", "module_base", "views_base", "registry", "wrapper_base"]

We tested it and it is working.

**Comment by vsoch** [comment]
Care to open a PR to fix this?

**Comment by vsoch** [comment]
@theklaloizou the way you typically do a pull request to a repository is to:

1. Fork the repository to your account
2. Clone the main branch
3. Create a feature branch for your change
4. Make the change and then push your feature branch to GItHub
5. Open a pull request from your branch to main here.

Imagine if everyone needed write access to every project they contributed to? It would absolutely not be a sane thing to do. Let me know if you have any questions on the above - there are likely guides out there to help. And thank you!

**Comment by theklaloizou** [comment]
@vsoch sorry I am not so experienced with git :) I have opened my PR!

**Comment by vsoch** [comment]
Closed with #660 nice job @theklaloizou !
